
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_DTI_TRANSFER_PROTOCOL]([COD_DTI_TRANSFER_PROTOCOL], [DES_DTI_TRANSFER_PROTOCOL])
SELECT -2, N'Not Applicable' UNION ALL
SELECT -1, N'Unknnown' UNION ALL
SELECT 1, N'DBMS to DBMS direct connection' UNION ALL
SELECT 2, N'(S)FTP File Transport' UNION ALL
SELECT 3, N'XCOM File Transport' UNION ALL
SELECT 4, N'DBMS to ETL TOOL to DBMS connection' UNION ALL
SELECT 5, N'OS File Copy' UNION ALL
SELECT 6, N'Web Service' UNION ALL
SELECT 7, N'Email Attachment'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_DTI_TRANSFER_PROTOCOL]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

