
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_ATTRIBUTE_TYPE]([COD_ATTRIBUTE_TYPE], [DES_ATTRIBUTE_TYPE])
SELECT N'_?_', N'UNKNOWN ATTRIBUTE TYPE' UNION ALL
SELECT N'BIGINT', N'BIGINT' UNION ALL
SELECT N'BIT', N'BIT' UNION ALL
SELECT N'CHAR', N'CHAR' UNION ALL
SELECT N'DATE', N'DATE' UNION ALL
SELECT N'DATETIME', N'DATETIME' UNION ALL
SELECT N'DATETIME2', N'DATETIME2' UNION ALL
SELECT N'DECIMAL', N'DECIMAL' UNION ALL
SELECT N'FLOAT', N'FLOAT' UNION ALL
SELECT N'IMAGE', N'IMAGE' UNION ALL
SELECT N'INT', N'INT' UNION ALL
SELECT N'NCHAR', N'NCHAR' UNION ALL
SELECT N'NTEXT', N'NTEXT' UNION ALL
SELECT N'NUMERIC', N'NUMERIC' UNION ALL
SELECT N'REAL', N'REAL' UNION ALL
SELECT N'SMALLINT', N'SMALLINT' UNION ALL
SELECT N'SYSNAME', N'SYSNAME' UNION ALL
SELECT N'TEXT', N'TEXT' UNION ALL
SELECT N'TIME', N'TIME' UNION ALL
SELECT N'TINYINT', N'TINYINT' UNION ALL
SELECT N'UNIQUEIDENTIFIER', N'UNIQUEIDENTIFIER' UNION ALL
SELECT N'VARCHAR', N'VARCHAR'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_ATTRIBUTE_TYPE]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

