
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_ENTITY_TYPE]([COD_ENTITY_TYPE], [DES_ENTITY_TYPE])
SELECT N'_?_', N'UNKNOWN FILE TYPE' UNION ALL
SELECT N'AUDIO', N'AUDIO FILE' UNION ALL
SELECT N'MDDB', N'DBMS MULTIDIMENSIONAL TABLE OBJECT' UNION ALL
SELECT N'TABLE', N'DBMS RELATIONAL TABLE OBJECT' UNION ALL
SELECT N'TEXT', N'TEXT CONTAINING FILE' UNION ALL
SELECT N'VIDEO', N'VIDEO FILE'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_ENTITY_TYPE]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

