
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_GENDER]([IND_GENDER], [DES_GENDER])
SELECT N'#', N'NOT APPLICABLE' UNION ALL
SELECT N'?', N'UNKNOWN' UNION ALL
SELECT N'F', N'FEMALE' UNION ALL
SELECT N'M', N'MALE'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_GENDER]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

