
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_BOOLEAN]([IND_YES_NO], [DES_IND])
SELECT N'#', N'NOT APPLICABLE' UNION ALL
SELECT N'?', N'UNKOWN' UNION ALL
SELECT N'N', N'NO' UNION ALL
SELECT N'Y', N'YES'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_BOOLEAN]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

