
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_LOG_TYPE]([COD_LOG_TYPE], [DES_LOG_TYPE])
SELECT N'ERROR', N'error log type' UNION ALL
SELECT N'INFORMATION', N'Information type of log type'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_LOG_TYPE]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

