
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_SCENARIO]([COD_SCENARIO], [DES_SCENARIO], [M_UTC_RECORD_INSERTED])
SELECT 0, N'Association exists in SOR', '20121106 14:08:16.660' UNION ALL
SELECT 100, N'Association is generated by datamining model X with 95% liability', '20121106 14:08:39.960' UNION ALL
SELECT 101, N'Association is generated by datamining model X with 80% liability', '20121106 14:09:12.990'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_SCENARIO]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

