
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_FUNCTION_TYPE]([COD_FUNCTION_TYPE], [DES_FUNCTION_TYPE])
SELECT N'FUNCTION', N'STORED FUNCTION' UNION ALL
SELECT N'PROCEDURE', N'STORED PROCEDURE'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_FUNCTION_TYPE]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

