
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_DTI_CONTAINER_TYPE]([COD_DTI_CONTAINER_TYPE], [DES_DTI_CONTAINER_TYPE])
SELECT -2, N'NOT APPLICABLE' UNION ALL
SELECT -1, N'UNKNOWN FILE' UNION ALL
SELECT 1, N'ASCII FLAT FILE' UNION ALL
SELECT 2, N'EBCDIC FLAT FILE' UNION ALL
SELECT 3, N'ASCII XML FILE' UNION ALL
SELECT 11, N'COMPRESSED ASCII FLAT FILE' UNION ALL
SELECT 12, N'COMPRESSED EBCDIC FLAT FILE' UNION ALL
SELECT 13, N'COMPRESSED ASCII XML FILE' UNION ALL
SELECT 14, N'COMPRESSED BINAIRY FILE' UNION ALL
SELECT 101, N'SPECIFIC BINAIRY FILE' UNION ALL
SELECT 102, N'GENERIC BINAIRY .XLS FILE (MS EXCEL)' UNION ALL
SELECT 103, N'GENERIC BINAIRY .XLSX FILE (MS EXCEL)' UNION ALL
SELECT 104, N'GENERIC BINAIRY .MDB FILE (MS ACCES)'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_DTI_CONTAINER_TYPE]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

