SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[VERSION]([COD_VERSION], [DAT_VERSION], [DES_VERSION])
SELECT 1, '20120831 00:00:00.000', N'DIKW DWH Accelerator metadata and generic functions, release 20120831.001.'
COMMIT;
RAISERROR (N'[MDAPEL].[VERSION]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

