
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_INPUT_OUTPUT]([IND_INPUT_OUTPUT], [DES_INPUT_OUTPUT])
SELECT N'I', N'INPUT' UNION ALL
SELECT N'O', N'OUTPUT'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_INPUT_OUTPUT]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

