
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [MDAPEL].[DOM_SUBJECT_TYPE]([COD_SUBJECT_TYPE], [DES_SUBJECT_TYPE])
SELECT N'_?_', N'UNKOWN SUBJECT TYPE' UNION ALL
SELECT N'DATABASE_SCHEME', N'SCHEMA IN AN RELATIONAL DATABASE' UNION ALL
SELECT N'META_INFORMATION', N'VICTICIOUS SUBJECT FOR DOCUMENTATION PURPOSES ONLY' UNION ALL
SELECT N'OS_FOLDER', N'OPERATING SYSTEM FOLDER / DIRECTORY / LIBRARY' UNION ALL
SELECT N'SHAREPOINT_SITE', N'SITE STRUCTURE IN AN SHAREPOINT ENVIRONMENT'
COMMIT;
RAISERROR (N'[MDAPEL].[DOM_SUBJECT_TYPE]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

