/****** Object:  StoredProcedure [MDAPEL].[GF_1002_GENERIC_POST_PROCESS]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [MDAPEL].[GF_1002_GENERIC_POST_PROCESS]
 @M_COD_PROCESS    BIGINT
,@M_COD_INSTANCE   BIGINT 
,@M_PROCESS_STATUS NVARCHAR(22)
----------------------------------------------------------------------------------
-- Author         : Michael Doves
-- Author Contact : michael.doves@dikw.com
-- Version        : 1
-- Creation Date  : 2012-06-08
-- Version Date   : 2012-06-08
-- Description    : Generic Post Handling of an instance of a process.
-- Modification   : 2012-06-08 Version 1: Initial Code
-- Copyrights	      : Copyright © DIKW Consulting B.V. 2013 All Rights Reserved. 
-- 			No part of this code may be reproduced without DIKW Consulting B.V.express consent.
----------------------------------------------------------------------------------
-- Example call: 'EXECUTE MDAPEL.GF_101_GENERIC_PRE_PROCESS @M_COD_PROCESS,@M_COD_INSTANCE'
AS
-- BEGIN: BEGIN TRY
BEGIN TRY
--   ENDL BEGIN TRY

-- BEGIN DECLARE UTCDATE()
DECLARE @M_UTC DATETIME2(7) = (SELECT GETUTCDATE())
--   END DECLARE UTCDATE()

-- BEGIN: 'ACTIVATED AND UNLOCKED'
IF @M_PROCESS_STATUS = 'ACTIVATED AND UNLOCKED'
BEGIN

  -- BEGIN: STOP INSTANCE NORMALLY 
  UPDATE MDAPEL.INSTANCE
     SET UTC_INSTANCE_END      = @M_UTC
        ,COD_INSTANCE_STATUS   = 'FINNISHED'
        ,TIM_DURATION_INSTANCE = DATEDIFF(SS,UTC_INSTANCE_START,@M_UTC)
   WHERE COD_INSTANCE = @M_COD_INSTANCE				
  --   END: STOP INSTANCE NORMALLY
  
  -- BEGIN: UNLOCK PROCESS
  UPDATE MDAPEL.PROCESS
     SET IND_INSTANCE_RUNNING = 'N'
   WHERE COD_PROCESS = @M_COD_PROCESS	
  -- END UNLOCK PROCESS
  
  -- BEGIN: INSERT LOG
  EXECUTE MDAPEL.GF_1000_INSERT_LOG
   @M_COD_PROCESS
  ,@M_COD_INSTANCE
  ,'INFORMATION'
  ,'The instance has finnished corectly.'
  --   END: INSERT LOG
END 
--   END: 'ACTIVATED AND UNLOCKED'

-- BEGIN: 'DEACTIVATED'
IF @M_PROCESS_STATUS = 'DEACTIVATED'
BEGIN

  -- BEGIN: STOP INSTANCE NORMALLY 
  UPDATE MDAPEL.INSTANCE
     SET UTC_INSTANCE_END      = @M_UTC
        ,COD_INSTANCE_STATUS   = 'DEACTIVATED'
        ,TIM_DURATION_INSTANCE = DATEDIFF(SS,UTC_INSTANCE_START,@M_UTC)
   WHERE COD_INSTANCE = @M_COD_INSTANCE				
  --   END: STOP INSTANCE NORMALLY
  
  -- BEGIN: INSERT LOG
  EXECUTE MDAPEL.GF_1000_INSERT_LOG
   @M_COD_PROCESS
  ,@M_COD_INSTANCE
  ,'INFORMATION'
  ,'The process is deactivated.'
  --   END: INSERT LOG
END 
--   END: 'DEACTIVATED'

-- BEGIN: 'DEACTIVATED'
IF @M_PROCESS_STATUS = 'ACTIVATED BUT LOCKED'
BEGIN

  -- BEGIN: STOP INSTANCE NORMALLY 
  UPDATE MDAPEL.INSTANCE
     SET UTC_INSTANCE_END      = @M_UTC
        ,COD_INSTANCE_STATUS   = 'ACTIVATED BUT LOCKED'
        ,TIM_DURATION_INSTANCE = DATEDIFF(SS,UTC_INSTANCE_START,@M_UTC)
   WHERE COD_INSTANCE = @M_COD_INSTANCE				
  --   END: STOP INSTANCE NORMALLY
  
  -- BEGIN: INSERT LOG
  EXECUTE MDAPEL.GF_1000_INSERT_LOG
   @M_COD_PROCESS
  ,@M_COD_INSTANCE
  ,'INFORMATION'
  ,'The process is activated but locked.'
  --   END: INSERT LOG
END 
--   END: 'DEACTIVATED'

-- BEGIN: END TRY
END TRY
--   END: END TRY


-- BEGIN: END CATCH
BEGIN CATCH
  SELECT ERROR_MESSAGE()
  RETURN
END CATCH 
 -- END: END CATCH
