/****** Object:  Schema [DDADTI]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [DDADTI]
GO
/****** Object:  Schema [DSAFIC]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [DSAFIC]
GO
/****** Object:  Schema [DSAISA]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [DSAISA]
GO
/****** Object:  Schema [DSAOMA]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [DSAOMA]
GO
/****** Object:  Schema [DSARIC]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [DSARIC]
GO
/****** Object:  Schema [DSATMP]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [DSATMP]
GO
/****** Object:  Schema [MDAPEL]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [MDAPEL]
GO
/****** Object:  Schema [OMADIA]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [OMADIA]
GO
/****** Object:  Schema [OMAFIC]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [OMAFIC]
GO
/****** Object:  Schema [OMAMDM]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [OMAMDM]
GO
/****** Object:  Schema [OMARIC]    Script Date: 2/19/2013 12:38:16 PM ******/
CREATE SCHEMA [OMARIC]
GO



/****** Object:  Table [MDAPEL].[AREA]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[AREA](
	[COD_AREA] [nchar](3) NOT NULL,
	[DES_AREA] [nvarchar](400) NOT NULL,
	[IND_ACTIVATED] [nchar](1) NOT NULL,
 CONSTRAINT [PK00_AREA] PRIMARY KEY CLUSTERED 
(
	[COD_AREA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[ATTRIBUTE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[ATTRIBUTE](
	[COD_ATTRIBUTE] [nvarchar](408) NOT NULL,
	[COD_ENTITY] [nvarchar](107) NOT NULL,
	[NAM_ATTRIBUTE] [nvarchar](200) NOT NULL,
	[DES_ATTRIBUTE] [nvarchar](max) NOT NULL,
	[IND_ATTRIBUTE_IS_NULLABLE] [nchar](1) NOT NULL,
	[COD_ATTRIBUTE_TYPE] [nvarchar](50) NOT NULL,
	[NUM_ATTRIBUTE_MAXIMUM_LENGTH] [smallint] NOT NULL,
	[NUM_ATTRIBUTE_PRECISION] [tinyint] NOT NULL,
	[NUM_ATTRIBUTE_SCALE] [tinyint] NOT NULL,
	[COD_DOMAIN] [bigint] NOT NULL,
	[DAT_ATTRIBUTE_START] [date] NOT NULL,
	[DAT_ATTRIBUTE_END] [date] NOT NULL,
	[DAT_ATTRIBUTE_LAST_STATUS] [date] NOT NULL,
 CONSTRAINT [PK00_ATTRIBUTE] PRIMARY KEY CLUSTERED 
(
	[COD_ATTRIBUTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[ATTRIBUTE_PROCESS]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[ATTRIBUTE_PROCESS](
	[COD_ATTRIBUTE] [nvarchar](408) NOT NULL,
	[IND_INPUT_OUTPUT] [nchar](1) NOT NULL,
	[COD_PROCESS] [bigint] NOT NULL,
 CONSTRAINT [PK00_ATTRIBUTE_PROCESS] PRIMARY KEY CLUSTERED 
(
	[COD_ATTRIBUTE] ASC,
	[IND_INPUT_OUTPUT] ASC,
	[COD_PROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_ASSOCIATION]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_ASSOCIATION](
	[COD_ASSOCIATION] [bigint] NOT NULL,
	[COD_ASSOCIATION_RECURSIVE] [bigint] NOT NULL,
	[COD_HUB_ENTITY_1] [nvarchar](100) NOT NULL,
	[COD_HUB_ENTITY_2] [nvarchar](100) NOT NULL,
	[DES_ASSOCIATION] [nvarchar](400) NOT NULL,
	[M_COD_PROCESS] [bigint] NOT NULL,
	[M_UTC_RECORD_INSERTED] [datetime2](7) NOT NULL,
	[M_UTC_RECORD_UPDATED] [datetime2](7) NULL,
 CONSTRAINT [PK00_HUB_ASSOCIATION] PRIMARY KEY CLUSTERED 
(
	[COD_ASSOCIATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_ATTRIBUTE_TYPE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_ATTRIBUTE_TYPE](
	[COD_ATTRIBUTE_TYPE] [nvarchar](50) NOT NULL,
	[DES_ATTRIBUTE_TYPE] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_ATTRIBUTE_TYPE] PRIMARY KEY CLUSTERED 
(
	[COD_ATTRIBUTE_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_BOOLEAN]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_BOOLEAN](
	[IND_YES_NO] [nchar](1) NOT NULL,
	[DES_IND] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_BOOLEAN] PRIMARY KEY CLUSTERED 
(
	[IND_YES_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_DTI_CONTAINER_TYPE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_DTI_CONTAINER_TYPE](
	[COD_DTI_CONTAINER_TYPE] [bigint] NOT NULL,
	[DES_DTI_CONTAINER_TYPE] [nvarchar](400) NOT NULL,
 CONSTRAINT [PK00_DOM_CONTAINER_TYPE] PRIMARY KEY CLUSTERED 
(
	[COD_DTI_CONTAINER_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_DTI_FREQUENCY]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_DTI_FREQUENCY](
	[COD_DTI_FREQUENCY] [bigint] NOT NULL,
	[DES_DTI_FREQUENCY] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_DTI_FREQUENCY] PRIMARY KEY CLUSTERED 
(
	[COD_DTI_FREQUENCY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_DTI_TRANSFER_PROTOCOL]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_DTI_TRANSFER_PROTOCOL](
	[COD_DTI_TRANSFER_PROTOCOL] [bigint] NOT NULL,
	[DES_DTI_TRANSFER_PROTOCOL] [nvarchar](400) NOT NULL,
 CONSTRAINT [PK00_DOM_TRANSFER_PROTOCOL] PRIMARY KEY CLUSTERED 
(
	[COD_DTI_TRANSFER_PROTOCOL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_DTI_TYPE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_DTI_TYPE](
	[COD_DTI_TYPE] [bigint] NOT NULL,
	[DES_DTI_TYPE] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_DTI_TYPE] PRIMARY KEY CLUSTERED 
(
	[COD_DTI_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_ENTITY_TYPE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_ENTITY_TYPE](
	[COD_ENTITY_TYPE] [nvarchar](50) NOT NULL,
	[DES_ENTITY_TYPE] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_ENTITY_TYPE] PRIMARY KEY CLUSTERED 
(
	[COD_ENTITY_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_FUNCTION_TYPE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_FUNCTION_TYPE](
	[COD_FUNCTION_TYPE] [nvarchar](50) NOT NULL,
	[DES_FUNCTION_TYPE] [nvarchar](400) NOT NULL,
 CONSTRAINT [PK00_DOM_FUNCTION_TYPE] PRIMARY KEY CLUSTERED 
(
	[COD_FUNCTION_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_GENDER]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_GENDER](
	[IND_GENDER] [nchar](1) NOT NULL,
	[DES_GENDER] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_GENDER] PRIMARY KEY CLUSTERED 
(
	[IND_GENDER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_GENERIC_SPECIFIC]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_GENERIC_SPECIFIC](
	[IND_GENERIC_SPECIFIC] [nchar](1) NOT NULL,
	[DES_GENERIC_SPECIFIC] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_GENERIC_SPECIFIC] PRIMARY KEY CLUSTERED 
(
	[IND_GENERIC_SPECIFIC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_HUB_ENTITY]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_HUB_ENTITY](
	[COD_HUB_ENTITY] [nvarchar](100) NOT NULL,
	[DES_HUB_ENTITY_UK] [nvarchar](max) NOT NULL,
	[DES_HUB_ENTITY_NL] [nvarchar](max) NULL,
 CONSTRAINT [PK00_DOM_HUB_ENTITY] PRIMARY KEY CLUSTERED 
(
	[COD_HUB_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_HUB_IDC]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_HUB_IDC](
	[IDC] [bigint] IDENTITY(-4,1) NOT NULL,
	[M_COD_SOR] [bigint] NOT NULL,
	[IDI] [nvarchar](100) NOT NULL,
	[COD_HUB_ENTITY] [nvarchar](100) NOT NULL,
	[M_COD_PROCESS] [bigint] NOT NULL,
	[M_UTC_RECORD_INSERTED] [datetime2](7) NOT NULL,
	[M_UTC_RECORD_UPDATED] [datetime2](7) NULL,
 CONSTRAINT [PK00_DOM_HUB_IDC] PRIMARY KEY CLUSTERED 
(
	[IDC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_INPUT_OUTPUT]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_INPUT_OUTPUT](
	[IND_INPUT_OUTPUT] [nchar](1) NOT NULL,
	[DES_INPUT_OUTPUT] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_INPU_OUTPUT] PRIMARY KEY CLUSTERED 
(
	[IND_INPUT_OUTPUT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_INSTANCE_STATUS]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_INSTANCE_STATUS](
	[COD_INSTANCE_STATUS] [nvarchar](22) NOT NULL,
	[DES_INSTANCE_STATUS] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_INSTANCE_STATUS] PRIMARY KEY CLUSTERED 
(
	[COD_INSTANCE_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_LOG_TYPE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_LOG_TYPE](
	[COD_LOG_TYPE] [nvarchar](20) NOT NULL,
	[DES_LOG_TYPE] [nvarchar](400) NOT NULL,
 CONSTRAINT [PK00_DOM_LOG_TYPE] PRIMARY KEY CLUSTERED 
(
	[COD_LOG_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_OBJECTROLE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_OBJECTROLE](
	[COD_OBJECTROLE] [bigint] NOT NULL,
	[COD_HUB_ENTITY] [nvarchar](100) NOT NULL,
	[DES_OBJECTROLE_UK] [nvarchar](400) NOT NULL,
	[DES_OBJECTROLE_NL] [nvarchar](400) NULL,
	[M_COD_PROCESS] [bigint] NOT NULL,
	[M_UTC_RECORD_INSERTED] [datetime2](7) NOT NULL,
	[M_UTC_RECORD_UPDATED] [datetime2](7) NULL,
 CONSTRAINT [PK00_DOM_OBJECTROLE] PRIMARY KEY CLUSTERED 
(
	[COD_OBJECTROLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_PLAUSIBLE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_PLAUSIBLE](
	[COD_PLAUSIBLE] [nchar](1) NOT NULL,
	[DES_PLAUSIBLE] [nvarchar](400) NOT NULL,
 CONSTRAINT [PK00_DOM_PLAUSIBLE] PRIMARY KEY CLUSTERED 
(
	[COD_PLAUSIBLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_PROCESS_ENGINE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_PROCESS_ENGINE](
	[COD_PROCESS_ENGINE] [bigint] NOT NULL,
	[NAM_PROCESS_ENGINE] [nvarchar](50) NOT NULL,
	[DES_PROCESS_ENGINE] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK00_DOM_PROCESS_TYPE] PRIMARY KEY CLUSTERED 
(
	[COD_PROCESS_ENGINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_QTY_DOMAIN_FROM]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_QTY_DOMAIN_FROM](
	[QTY_DOMAIN_FROM] [smallint] NOT NULL,
 CONSTRAINT [PK00_DOM_QTY_DOMAIN_FROM] PRIMARY KEY CLUSTERED 
(
	[QTY_DOMAIN_FROM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_SCENARIO]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_SCENARIO](
	[COD_SCENARIO] [bigint] NOT NULL,
	[DES_SCENARIO] [nvarchar](400) NOT NULL,
	[M_UTC_RECORD_INSERTED] [datetime2](7) NOT NULL,
 CONSTRAINT [PK00_DOM_SCENARIO] PRIMARY KEY CLUSTERED 
(
	[COD_SCENARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOM_SUBJECT_TYPE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_SUBJECT_TYPE](
	[COD_SUBJECT_TYPE] [nvarchar](50) NOT NULL,
	[DES_SUBJECT_TYPE] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_SUBJECT_TYPE] PRIMARY KEY CLUSTERED 
(
	[COD_SUBJECT_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOMAIN]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOMAIN](
	[COD_DOMAIN] [bigint] NOT NULL,
	[IND_GENERIC_SPECIFIC] [nchar](1) NOT NULL,
	[COD_SOR] [bigint] NOT NULL,
	[COD_DOMAIN_MASK] [nvarchar](50) NOT NULL,
	[NAM_DOMAIN] [nvarchar](200) NOT NULL,
	[DES_DOMAIN] [nvarchar](max) NOT NULL,
	[DAT_START] [date] NOT NULL,
	[DAT_END] [date] NOT NULL,
 CONSTRAINT [PK00_DOMAIN] PRIMARY KEY CLUSTERED 
(
	[COD_DOMAIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOMAIN_TRANSLATION]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOMAIN_TRANSLATION](
	[COD_DOMAIN_TRANSLATION] [bigint] NOT NULL,
	[QTY_DOMAIN_FROM] [smallint] NOT NULL,
	[COD_DOMAIN_FROM_01] [bigint] NOT NULL,
	[COD_DOMAIN_FROM_02] [bigint] NOT NULL,
	[COD_DOMAIN_FROM_03] [bigint] NOT NULL,
	[COD_DOMAIN_FROM_04] [bigint] NOT NULL,
	[COD_DOMAIN_FROM_05] [bigint] NOT NULL,
	[COD_DOMAIN_TOO] [bigint] NOT NULL,
	[DAT_START] [date] NOT NULL,
	[DAT_END] [date] NOT NULL,
 CONSTRAINT [PK00_DOMAIN_TRANSLATION] PRIMARY KEY CLUSTERED 
(
	[COD_DOMAIN_TRANSLATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOMAIN_TRANSLATION_VALUE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE](
	[COD_DOMAIN_TRANSLATION] [bigint] NOT NULL,
	[COD_DOMAIN_VALUE_FROM_01] [nvarchar](50) NOT NULL,
	[COD_DOMAIN_VALUE_FROM_02] [nvarchar](50) NOT NULL,
	[COD_DOMAIN_VALUE_FROM_03] [nvarchar](50) NOT NULL,
	[COD_DOMAIN_VALUE_FROM_04] [nvarchar](50) NOT NULL,
	[COD_DOMAIN_VALUE_FROM_05] [nvarchar](50) NOT NULL,
	[COD_DOMAIN_VALUE_TOO] [nvarchar](50) NOT NULL,
	[DAT_START] [date] NOT NULL,
	[DAT_END] [date] NOT NULL,
 CONSTRAINT [PK00_DOMAIN_TRANSLATION_VALUE] PRIMARY KEY CLUSTERED 
(
	[COD_DOMAIN_TRANSLATION] ASC,
	[COD_DOMAIN_VALUE_FROM_01] ASC,
	[COD_DOMAIN_VALUE_FROM_02] ASC,
	[COD_DOMAIN_VALUE_FROM_03] ASC,
	[COD_DOMAIN_VALUE_FROM_04] ASC,
	[COD_DOMAIN_VALUE_FROM_05] ASC,
	[COD_DOMAIN_VALUE_TOO] ASC,
	[DAT_START] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DOMAIN_VALUE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOMAIN_VALUE](
	[COD_DOMAIN] [bigint] NOT NULL,
	[COD_DOMAIN_VALUE] [nvarchar](50) NOT NULL,
	[DES_DOMAIN_VALUE] [nvarchar](400) NOT NULL,
	[DAT_START] [date] NOT NULL,
	[DAT_END] [date] NOT NULL,
	[DES_DOMAIN_VALUE_NL] [nvarchar](400) NULL,
	[DES_REMARK] [nvarchar](max) NULL,
 CONSTRAINT [PK00_DOMAIN_VALUE] PRIMARY KEY CLUSTERED 
(
	[COD_DOMAIN] ASC,
	[COD_DOMAIN_VALUE] ASC,
	[DAT_START] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[DTI]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DTI](
	[COD_DTI] [bigint] NOT NULL,
	[COD_ENTITY] [nvarchar](107) NOT NULL,
	[COD_SOR] [bigint] NOT NULL,
	[COD_DTI_TYPE] [bigint] NOT NULL,
	[COD_DTI_CONTAINER_TYPE] [bigint] NOT NULL,
	[COD_DTI_FREQUENCY] [bigint] NOT NULL,
	[COD_DTI_TRANSFER_PROTOCOL] [bigint] NOT NULL,
	[DES_DTI] [nvarchar](max) NOT NULL,
	[IND_ACTIVATED] [nchar](1) NOT NULL,
 CONSTRAINT [PK00_DTI] PRIMARY KEY CLUSTERED 
(
	[COD_DTI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[ENTITY]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[ENTITY](
	[COD_ENTITY] [nvarchar](107) NOT NULL,
	[COD_SUBJECT] [nchar](6) NOT NULL,
	[NAM_ENTITY] [nvarchar](200) NOT NULL,
	[COD_ENTITY_TYPE] [nvarchar](50) NOT NULL,
	[DES_ENTITY] [nvarchar](max) NULL,
	[DES_DESIGN_REMARKS] [nvarchar](max) NULL,
	[DAT_ENTITY_START] [date] NOT NULL,
	[DAT_ENTITY_END] [date] NOT NULL,
	[DAT_ENTITY_LAST_STATUS] [date] NOT NULL,
	[QTY_NUMBER_OF_ROWS] [bigint] NOT NULL,
	[QTY_DATA_SPACE_IN_KB] [bigint] NOT NULL,
	[QTY_INDEX_SPACE_IN_KB] [bigint] NOT NULL,
	[QTY_UNUSED_SPACE_IN_KB] [bigint] NOT NULL,
	[QTY_TOTAL_SPACE_IN_KB] [bigint] NOT NULL,
 CONSTRAINT [PK00_ENTITY] PRIMARY KEY CLUSTERED 
(
	[COD_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT](
	[COD_ENTITY] [nvarchar](107) NOT NULL,
	[COD_SOR] [bigint] NOT NULL,
	[DAT_SNAPSHOT] [datetime2](0) NOT NULL,
	[UTC_RECORD_INSERTED] [datetime2](0) NOT NULL,
 CONSTRAINT [PK00_ENTITY_PROCESSED_SNAPSHOTS_DAT] PRIMARY KEY CLUSTERED 
(
	[COD_ENTITY] ASC,
	[COD_SOR] ASC,
	[DAT_SNAPSHOT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC](
	[COD_ENTITY] [nvarchar](107) NOT NULL,
	[COD_SOR] [bigint] NOT NULL,
	[UTC_SNAPSHOT] [datetime2](0) NOT NULL,
	[UTC_RECORD_INSERTED] [datetime2](0) NOT NULL,
 CONSTRAINT [PK00_ENTITY_PROCESSED_SNAPSHOTS_UTC] PRIMARY KEY CLUSTERED 
(
	[COD_ENTITY] ASC,
	[COD_SOR] ASC,
	[UTC_SNAPSHOT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[FUNCTION]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[FUNCTION](
	[COD_FUNCTION] [bigint] NOT NULL,
	[COD_SUBJECT] [nchar](6) NOT NULL,
	[IND_GENERIC_SPECIFIC] [nchar](1) NOT NULL,
	[NAM_FUNCTION] [nvarchar](200) NOT NULL,
	[DES_FUNCTION] [nvarchar](4000) NOT NULL,
	[COD_FUNCTION_TYPE] [nvarchar](50) NOT NULL,
	[QTY_VERSION_NUMBER] [int] NOT NULL,
	[DAT_VERSION_DATE] [date] NOT NULL,
 CONSTRAINT [PK00_FUNCTION] PRIMARY KEY CLUSTERED 
(
	[COD_FUNCTION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[FUNCTION_PROCESS]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[FUNCTION_PROCESS](
	[COD_FUNCTION] [bigint] NOT NULL,
	[COD_PROCESS] [bigint] NOT NULL,
 CONSTRAINT [PK00_FUNCTION_PROCESS] PRIMARY KEY CLUSTERED 
(
	[COD_FUNCTION] ASC,
	[COD_PROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[INSTANCE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[INSTANCE](
	[COD_INSTANCE] [bigint] IDENTITY(1,1) NOT NULL,
	[COD_PROCESS] [bigint] NOT NULL,
	[COD_INSTANCE_STATUS] [nvarchar](22) NOT NULL,
	[UTC_INSTANCE_START] [datetime2](7) NOT NULL,
	[UTC_INSTANCE_END] [datetime2](7) NULL,
	[TIM_DURATION_INSTANCE] [bigint] NULL,
 CONSTRAINT [PK00_INSTANCE] PRIMARY KEY CLUSTERED 
(
	[COD_INSTANCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[LOG]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[LOG](
	[IDR_LOG] [bigint] IDENTITY(1,1) NOT NULL,
	[COD_PROCESS] [bigint] NOT NULL,
	[COD_INSTANCE] [bigint] NOT NULL,
	[UTC_LOG] [datetime2](7) NOT NULL,
	[COD_LOG_TYPE] [nvarchar](20) NOT NULL,
	[TXT_LOG] [nvarchar](4000) NOT NULL,
 CONSTRAINT [PK00_LOG] PRIMARY KEY CLUSTERED 
(
	[IDR_LOG] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[PROCESS]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[PROCESS](
	[COD_PROCESS] [bigint] NOT NULL,
	[COD_SUBJECT] [nchar](6) NOT NULL,
	[IND_INSTANCE_RUNNING] [nchar](1) NOT NULL,
	[IND_ACTIVATED] [nchar](1) NOT NULL,
	[COD_PROCESS_ENGINE] [bigint] NOT NULL,
	[NAM_PROCESS] [nvarchar](200) NOT NULL,
	[DES_PROCESS] [nvarchar](400) NOT NULL,
 CONSTRAINT [PK00_PROCESS] PRIMARY KEY CLUSTERED 
(
	[COD_PROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[SOR]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[SOR](
	[COD_SOR] [bigint] NOT NULL,
	[COD_SUBJECT] [nchar](6) NOT NULL,
	[DES_SOR] [nvarchar](400) NOT NULL,
	[DAT_START] [date] NOT NULL,
	[DAT_END] [date] NOT NULL,
	[NAM_SOR_MAINTAINER] [nvarchar](200) NULL,
	[IDE_EMAIL_MAINTAINER] [nvarchar](100) NULL,
	[IDE_PHONE_MAINTAINER] [nvarchar](20) NULL,
	[DES_REMARK] [nvarchar](400) NULL,
 CONSTRAINT [PK00_SOR] PRIMARY KEY CLUSTERED 
(
	[COD_SOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[SUBJECT]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[SUBJECT](
	[COD_SUBJECT] [nchar](6) NOT NULL,
	[COD_AREA] [nchar](3) NOT NULL,
	[COD_SUBJECT_TYPE] [nvarchar](50) NOT NULL,
	[DES_SUBJECT] [nvarchar](400) NOT NULL,
	[IND_ACTIVATED] [nchar](1) NOT NULL,
 CONSTRAINT [PK00_SUBJECT] PRIMARY KEY CLUSTERED 
(
	[COD_SUBJECT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[USER]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[USER](
	[COD_USER] [bigint] IDENTITY(1,1) NOT NULL,
	[NAM_LOGIN] [nvarchar](200) NOT NULL,
	[COD_PASSWORD] [nvarchar](50) NOT NULL,
	[NAM_FIRST_NAMES] [nvarchar](200) NOT NULL,
	[NAM_LAST_NAME_PREFIX] [nvarchar](50) NULL,
	[NAM_LAST_NAME] [nvarchar](200) NOT NULL,
	[IND_GENDER] [nchar](1) NOT NULL,
	[DAT_OF_BIRTH] [date] NOT NULL,
	[IDE_PHONENUMBER_01] [nvarchar](20) NULL,
	[IDE_PHONENUMBER_02] [nvarchar](20) NULL,
	[IDE_EMAIL_01] [nvarchar](200) NULL,
	[IDE_EMAIL_02] [nvarchar](200) NULL,
	[IND_ACTIVATED] [nchar](1) NOT NULL,
 CONSTRAINT [PK00_USER] PRIMARY KEY CLUSTERED 
(
	[COD_USER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [MDAPEL].[VERSION]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[VERSION](
	[COD_VERSION] [int] NOT NULL,
	[DAT_VERSION] [date] NOT NULL,
	[DES_VERSION] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK00_VERSION] PRIMARY KEY CLUSTERED 
(
	[COD_VERSION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  View [MDAPEL].[VW_INFRASTRUCTURE_SIZE_ENTITY]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [MDAPEL].[VW_INFRASTRUCTURE_SIZE_ENTITY] 
AS
SELECT 
 COD_SUBJECT
,NAM_ENTITY
,SUM(QTY_NUMBER_OF_ROWS) AS QTY_NUMBER_OF_ROWS
,SUM(QTY_DATA_SPACE_IN_KB/1024/1024)  AS QTY_DATA_SPACE_IN_GB
,SUM(QTY_INDEX_SPACE_IN_KB/1024/1024) AS QTY_INDEX_SPACE_IN_GB
,SUM(QTY_UNUSED_SPACE_IN_KB/1024/1024) AS QTY_UNUSED_SPACE_IN_GB
,SUM(QTY_TOTAL_SPACE_IN_KB/1024/1024) AS QTY_TOTAL_SPACE_IN_GB
  FROM MDAPEL.ENTITY
 WHERE 1=1 
GROUP BY COD_SUBJECT,NAM_ENTITY

GO
/****** Object:  View [MDAPEL].[VW_INFRASTRUCTURE_SIZE_SUBJECT]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [MDAPEL].[VW_INFRASTRUCTURE_SIZE_SUBJECT] 
AS
SELECT 
 COD_SUBJECT
,SUM(QTY_NUMBER_OF_ROWS) AS QTY_NUMBER_OF_ROWS
,SUM(QTY_DATA_SPACE_IN_KB/1024/1024)  AS QTY_DATA_SPACE_IN_GB
,SUM(QTY_INDEX_SPACE_IN_KB/1024/1024) AS QTY_INDEX_SPACE_IN_GB
,SUM(QTY_UNUSED_SPACE_IN_KB/1024/1024) AS QTY_UNUSED_SPACE_IN_GB
,SUM(QTY_TOTAL_SPACE_IN_KB/1024/1024) AS QTY_TOTAL_SPACE_IN_GB
  FROM MDAPEL.ENTITY
 WHERE 1=1 
GROUP BY COD_SUBJECT

GO
/****** Object:  View [MDAPEL].[VW_INFRASTRUCTURE_SIZE_TOTAL]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [MDAPEL].[VW_INFRASTRUCTURE_SIZE_TOTAL] 
AS
SELECT 
 SUM(QTY_NUMBER_OF_ROWS) AS QTY_NUMBER_OF_ROWS
,SUM(QTY_DATA_SPACE_IN_KB/1024/1024)  AS QTY_DATA_SPACE_IN_GB
,SUM(QTY_INDEX_SPACE_IN_KB/1024/1024) AS QTY_INDEX_SPACE_IN_GB
,SUM(QTY_UNUSED_SPACE_IN_KB/1024/1024) AS QTY_UNUSED_SPACE_IN_GB
,SUM(QTY_TOTAL_SPACE_IN_KB/1024/1024) AS QTY_TOTAL_SPACE_IN_GB
--select *
  FROM MDAPEL.ENTITY
 WHERE 1=1

GO
/****** Object:  View [MDAPEL].[VW_INSTANCE_LOG]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [MDAPEL].[VW_INSTANCE_LOG] 
AS
SELECT 
 [INSTANCE].COD_PROCESS
,[INSTANCE].COD_INSTANCE
,[PROCESS].IND_INSTANCE_RUNNING
,[INSTANCE].COD_INSTANCE_STATUS
,[INSTANCE].UTC_INSTANCE_START
,[INSTANCE].UTC_INSTANCE_END
,[INSTANCE].TIM_DURATION_INSTANCE
,[PROCESS].COD_SUBJECT
,[PROCESS].NAM_PROCESS
  FROM
(
SELECT *
  FROM [MDAPEL].[INSTANCE]
) [INSTANCE]
INNER JOIN
(
SELECT *
  FROM MDAPEL.PROCESS
) [PROCESS]
ON [INSTANCE].[COD_PROCESS] = [PROCESS].[COD_PROCESS]

GO
/****** Object:  View [MDAPEL].[VW_LOG]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [MDAPEL].[VW_LOG] 
AS
SELECT 
 [LOG].IDR_LOG
,[LOG].COD_PROCESS
,[LOG].COD_INSTANCE
,[INSTANCE].COD_INSTANCE_STATUS
,[PROCESS].NAM_PROCESS
,[PROCESS].COD_SUBJECT
,[PROCESS].IND_INSTANCE_RUNNING
,[INSTANCE].UTC_INSTANCE_START
,[INSTANCE].UTC_INSTANCE_END
,[LOG].COD_LOG_TYPE
,[LOG].UTC_LOG
,[LOG].TXT_LOG 
  FROM
(
SELECT *
  FROM [MDAPEL].[LOG]
) [LOG]
INNER JOIN
(
SELECT *
  FROM [MDAPEL].[INSTANCE]
) [INSTANCE]
ON [LOG].[COD_INSTANCE] = [INSTANCE].[COD_INSTANCE]
INNER JOIN
(
SELECT *
  FROM MDAPEL.PROCESS
) [PROCESS]
ON [LOG].[COD_PROCESS] = [PROCESS].[COD_PROCESS]

GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK03_ATTRIBUTE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK03_ATTRIBUTE] ON [MDAPEL].[ATTRIBUTE]
(
	[COD_ENTITY] ASC,
	[NAM_ATTRIBUTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX03_DOMAIN_TRANSLATION_VALUE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX03_DOMAIN_TRANSLATION_VALUE] ON [MDAPEL].[DOMAIN_TRANSLATION_VALUE]
(
	[COD_DOMAIN_TRANSLATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK02_DOMAIN_TRANSLATION_VALUE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK02_DOMAIN_TRANSLATION_VALUE] ON [MDAPEL].[DOMAIN_TRANSLATION_VALUE]
(
	[COD_DOMAIN_TRANSLATION] ASC,
	[COD_DOMAIN_VALUE_FROM_01] ASC,
	[COD_DOMAIN_VALUE_FROM_02] ASC,
	[COD_DOMAIN_VALUE_FROM_03] ASC,
	[COD_DOMAIN_VALUE_FROM_04] ASC,
	[COD_DOMAIN_VALUE_FROM_05] ASC,
	[COD_DOMAIN_VALUE_TOO] ASC,
	[DAT_END] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK01_ENTITY]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK01_ENTITY] ON [MDAPEL].[ENTITY]
(
	[COD_SUBJECT] ASC,
	[NAM_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX02_ENTITY_PROCESSED_SNAPSHOTS_DAT]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX02_ENTITY_PROCESSED_SNAPSHOTS_DAT] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]
(
	[COD_SOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX03_ENTITY_PROCESSED_SNAPSHOTS_DAT]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX03_ENTITY_PROCESSED_SNAPSHOTS_DAT] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]
(
	[DAT_SNAPSHOT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX04_ENTITY_PROCESSED_SNAPSHOTS_DAT]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX04_ENTITY_PROCESSED_SNAPSHOTS_DAT] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]
(
	[COD_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX02_ENTITY_PROCESSED_SNAPSHOTS_UTC]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX02_ENTITY_PROCESSED_SNAPSHOTS_UTC] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]
(
	[COD_SOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX03_ENTITY_PROCESSED_SNAPSHOTS_UTC]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX03_ENTITY_PROCESSED_SNAPSHOTS_UTC] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]
(
	[UTC_SNAPSHOT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX04_ENTITY_PROCESSED_SNAPSHOTS_UTC]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX04_ENTITY_PROCESSED_SNAPSHOTS_UTC] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]
(
	[COD_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX01_INSTANCE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX01_INSTANCE] ON [MDAPEL].[INSTANCE]
(
	[COD_PROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX10_LOG_COD_PROCESS]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX10_LOG_COD_PROCESS] ON [MDAPEL].[LOG]
(
	[COD_PROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX11_LOG_COD_INSTANCE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX11_LOG_COD_INSTANCE] ON [MDAPEL].[LOG]
(
	[COD_INSTANCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX12_LOG_COD_LOG_TYPE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX12_LOG_COD_LOG_TYPE] ON [MDAPEL].[LOG]
(
	[COD_LOG_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] ADD  CONSTRAINT [CN04_HUB_ASSOCIATION]  DEFAULT ((0)) FOR [COD_ASSOCIATION_RECURSIVE]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] ADD  CONSTRAINT [CN02_HUB_ASSOCIATION]  DEFAULT ((0)) FOR [M_COD_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] ADD  CONSTRAINT [CN03_HUB_ASSOCIATION]  DEFAULT (getutcdate()) FOR [M_UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC] ADD  CONSTRAINT [CN01_DOM_HUB_IDC]  DEFAULT (getutcdate()) FOR [M_UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE] ADD  CONSTRAINT [CN02_HUB_OBJECTROLE]  DEFAULT ((0)) FOR [M_COD_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE] ADD  CONSTRAINT [CN03_HUB_OBJECTROLE]  DEFAULT (getutcdate()) FOR [M_UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[DOM_SCENARIO] ADD  CONSTRAINT [CN01_DOM_SCENARIO]  DEFAULT (getutcdate()) FOR [M_UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((1)) FOR [QTY_DOMAIN_FROM]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((-2)) FOR [COD_DOMAIN_FROM_02]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((-2)) FOR [COD_DOMAIN_FROM_03]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((-2)) FOR [COD_DOMAIN_FROM_04]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((-2)) FOR [COD_DOMAIN_FROM_05]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__0D3AD6BB]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_01]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__0E2EFAF4]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_02]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__0F231F2D]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_03]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__10174366]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_04]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__110B679F]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_05]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__16C440F5]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_TOO]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT] ADD  CONSTRAINT [CN01_ENTITY_PROCESSED_SNAPSHOTS_DAT_M_UTC_RECORD_INSERTED]  DEFAULT (getutcdate()) FOR [UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC] ADD  CONSTRAINT [CN01_ENTITY_PROCESSED_SNAPSHOTS_UTC_M_UTC_RECORD_INSERTED]  DEFAULT (getutcdate()) FOR [UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[LOG] ADD  CONSTRAINT [CN09_LOG_UTCDATE]  DEFAULT (getutcdate()) FOR [UTC_LOG]
GO
ALTER TABLE [MDAPEL].[AREA]  WITH CHECK ADD  CONSTRAINT [FK01_AREA_TO_DOMAIN_BOOLEAN] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[AREA] CHECK CONSTRAINT [FK01_AREA_TO_DOMAIN_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK01_ATTRIBUTE_TO_ENTITY] FOREIGN KEY([COD_ENTITY])
REFERENCES [MDAPEL].[ENTITY] ([COD_ENTITY])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [FK01_ATTRIBUTE_TO_ENTITY]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK02_ATTRIBUTE_TO_DOM_BOOLEAN] FOREIGN KEY([IND_ATTRIBUTE_IS_NULLABLE])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [FK02_ATTRIBUTE_TO_DOM_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK04_ATTRIBUTE_TO_DOM_ATTRIBUTE_TYPE] FOREIGN KEY([COD_ATTRIBUTE_TYPE])
REFERENCES [MDAPEL].[DOM_ATTRIBUTE_TYPE] ([COD_ATTRIBUTE_TYPE])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [FK04_ATTRIBUTE_TO_DOM_ATTRIBUTE_TYPE]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK05_ATTRIBUTE_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [FK05_ATTRIBUTE_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK01_ATTRIBUTE_PROCESS_TO_ATTRIBUTE] FOREIGN KEY([COD_ATTRIBUTE])
REFERENCES [MDAPEL].[ATTRIBUTE] ([COD_ATTRIBUTE])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS] CHECK CONSTRAINT [FK01_ATTRIBUTE_PROCESS_TO_ATTRIBUTE]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK02_ATTRIBUTE_PROCESS_TO_PROCESS] FOREIGN KEY([COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS] CHECK CONSTRAINT [FK02_ATTRIBUTE_PROCESS_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK03_ATTRIBUTE_PROCESS_TO_DOM_INPUT_OUTPUT] FOREIGN KEY([IND_INPUT_OUTPUT])
REFERENCES [MDAPEL].[DOM_INPUT_OUTPUT] ([IND_INPUT_OUTPUT])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS] CHECK CONSTRAINT [FK03_ATTRIBUTE_PROCESS_TO_DOM_INPUT_OUTPUT]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [FK01_DOM_ASSOCIATION_TO_MDAPEL_PROCESS] FOREIGN KEY([M_COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] CHECK CONSTRAINT [FK01_DOM_ASSOCIATION_TO_MDAPEL_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [FK02_DOM_ASSOCIATION_TO_DOM_ASSOCIATION] FOREIGN KEY([COD_ASSOCIATION_RECURSIVE])
REFERENCES [MDAPEL].[DOM_ASSOCIATION] ([COD_ASSOCIATION])
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] CHECK CONSTRAINT [FK02_DOM_ASSOCIATION_TO_DOM_ASSOCIATION]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [FK03_DOM_ASSOCIATION_TO_DOM_HUB_ENTITY] FOREIGN KEY([COD_HUB_ENTITY_1])
REFERENCES [MDAPEL].[DOM_HUB_ENTITY] ([COD_HUB_ENTITY])
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] CHECK CONSTRAINT [FK03_DOM_ASSOCIATION_TO_DOM_HUB_ENTITY]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [FK04_DOM_ASSOCIATION_TO_DOM_HUB_ENTITY] FOREIGN KEY([COD_HUB_ENTITY_2])
REFERENCES [MDAPEL].[DOM_HUB_ENTITY] ([COD_HUB_ENTITY])
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] CHECK CONSTRAINT [FK04_DOM_ASSOCIATION_TO_DOM_HUB_ENTITY]
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC]  WITH CHECK ADD  CONSTRAINT [FK02_DOM_HUB_IDC_TO_PROCESS] FOREIGN KEY([M_COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC] CHECK CONSTRAINT [FK02_DOM_HUB_IDC_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC]  WITH CHECK ADD  CONSTRAINT [FK03_DOM_HUB_IDC_TO_SOR] FOREIGN KEY([M_COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC] CHECK CONSTRAINT [FK03_DOM_HUB_IDC_TO_SOR]
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC]  WITH CHECK ADD  CONSTRAINT [FK04_DOM_HUB_IDC_TO_DOM_HUB_ENTITY] FOREIGN KEY([COD_HUB_ENTITY])
REFERENCES [MDAPEL].[DOM_HUB_ENTITY] ([COD_HUB_ENTITY])
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC] CHECK CONSTRAINT [FK04_DOM_HUB_IDC_TO_DOM_HUB_ENTITY]
GO
ALTER TABLE [MDAPEL].[DOM_INSTANCE_STATUS]  WITH CHECK ADD  CONSTRAINT [FK_DOM_INSTANCE_STATUS_DOM_INSTANCE_STATUS] FOREIGN KEY([COD_INSTANCE_STATUS])
REFERENCES [MDAPEL].[DOM_INSTANCE_STATUS] ([COD_INSTANCE_STATUS])
GO
ALTER TABLE [MDAPEL].[DOM_INSTANCE_STATUS] CHECK CONSTRAINT [FK_DOM_INSTANCE_STATUS_DOM_INSTANCE_STATUS]
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE]  WITH CHECK ADD  CONSTRAINT [FK01_HUB_OBJECTROLE_TO_PROCESS] FOREIGN KEY([M_COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE] CHECK CONSTRAINT [FK01_HUB_OBJECTROLE_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE]  WITH CHECK ADD  CONSTRAINT [FK02_HUB_OBJECTROLE_TO_DOM_HUB_ENTITY] FOREIGN KEY([COD_HUB_ENTITY])
REFERENCES [MDAPEL].[DOM_HUB_ENTITY] ([COD_HUB_ENTITY])
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE] CHECK CONSTRAINT [FK02_HUB_OBJECTROLE_TO_DOM_HUB_ENTITY]
GO
ALTER TABLE [MDAPEL].[DOMAIN]  WITH CHECK ADD  CONSTRAINT [FK01_DOMAIN_TO_SOR] FOREIGN KEY([COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[DOMAIN] CHECK CONSTRAINT [FK01_DOMAIN_TO_SOR]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK01_DOMAIN_TRANSLATION_TO_DOM_QTY_DOMAIN_FROM] FOREIGN KEY([QTY_DOMAIN_FROM])
REFERENCES [MDAPEL].[DOM_QTY_DOMAIN_FROM] ([QTY_DOMAIN_FROM])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK01_DOMAIN_TRANSLATION_TO_DOM_QTY_DOMAIN_FROM]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK11_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_01])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK11_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK12_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_02])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK12_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK13_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_03])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK13_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK14_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_04])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK14_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK15_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_05])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK15_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK21_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_TOO])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK21_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE]  WITH CHECK ADD  CONSTRAINT [FK01_DOMAIN_TRANSLATION_VALUE] FOREIGN KEY([COD_DOMAIN_TRANSLATION])
REFERENCES [MDAPEL].[DOMAIN_TRANSLATION] ([COD_DOMAIN_TRANSLATION])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] CHECK CONSTRAINT [FK01_DOMAIN_TRANSLATION_VALUE]
GO
ALTER TABLE [MDAPEL].[DOMAIN_VALUE]  WITH CHECK ADD  CONSTRAINT [FK01_DOMAIN_VALUE_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_VALUE] CHECK CONSTRAINT [FK01_DOMAIN_VALUE_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK01_DTI_TO_ENTITY] FOREIGN KEY([COD_ENTITY])
REFERENCES [MDAPEL].[ENTITY] ([COD_ENTITY])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK01_DTI_TO_ENTITY]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK02_DTI_TO_SOR] FOREIGN KEY([COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK02_DTI_TO_SOR]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK03_DTI_TO_DOM_BOOLEAN] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK03_DTI_TO_DOM_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK04_DTI_TO_DOM_DTI_TYPE] FOREIGN KEY([COD_DTI_TYPE])
REFERENCES [MDAPEL].[DOM_DTI_TYPE] ([COD_DTI_TYPE])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK04_DTI_TO_DOM_DTI_TYPE]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK05_DTI_TO_DOM_DTI_CONTAINER_TYPE] FOREIGN KEY([COD_DTI_CONTAINER_TYPE])
REFERENCES [MDAPEL].[DOM_DTI_CONTAINER_TYPE] ([COD_DTI_CONTAINER_TYPE])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK05_DTI_TO_DOM_DTI_CONTAINER_TYPE]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK06_DTI_TO_DOM_DTI_FREQUENCY] FOREIGN KEY([COD_DTI_FREQUENCY])
REFERENCES [MDAPEL].[DOM_DTI_FREQUENCY] ([COD_DTI_FREQUENCY])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK06_DTI_TO_DOM_DTI_FREQUENCY]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK07_DTI_TO_DOM_DTI_TRANSFER_PROTOCOL] FOREIGN KEY([COD_DTI_TRANSFER_PROTOCOL])
REFERENCES [MDAPEL].[DOM_DTI_TRANSFER_PROTOCOL] ([COD_DTI_TRANSFER_PROTOCOL])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK07_DTI_TO_DOM_DTI_TRANSFER_PROTOCOL]
GO
ALTER TABLE [MDAPEL].[ENTITY]  WITH CHECK ADD  CONSTRAINT [FK02_ENTITY_TO_SUBJECT] FOREIGN KEY([COD_SUBJECT])
REFERENCES [MDAPEL].[SUBJECT] ([COD_SUBJECT])
GO
ALTER TABLE [MDAPEL].[ENTITY] CHECK CONSTRAINT [FK02_ENTITY_TO_SUBJECT]
GO
ALTER TABLE [MDAPEL].[ENTITY]  WITH CHECK ADD  CONSTRAINT [FK03_ENTITY_TO_DOM_ENTITY_TYPE] FOREIGN KEY([COD_ENTITY_TYPE])
REFERENCES [MDAPEL].[DOM_ENTITY_TYPE] ([COD_ENTITY_TYPE])
GO
ALTER TABLE [MDAPEL].[ENTITY] CHECK CONSTRAINT [FK03_ENTITY_TO_DOM_ENTITY_TYPE]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]  WITH CHECK ADD  CONSTRAINT [FK05_ENTITY_PROCESSED_SNAPSHOTS_DAT_TO_ENTITY] FOREIGN KEY([COD_ENTITY])
REFERENCES [MDAPEL].[ENTITY] ([COD_ENTITY])
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT] CHECK CONSTRAINT [FK05_ENTITY_PROCESSED_SNAPSHOTS_DAT_TO_ENTITY]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]  WITH CHECK ADD  CONSTRAINT [FK06_ENTITY_PROCESSED_SNAPSHOTS_DAT_TO_SOR] FOREIGN KEY([COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT] CHECK CONSTRAINT [FK06_ENTITY_PROCESSED_SNAPSHOTS_DAT_TO_SOR]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]  WITH CHECK ADD  CONSTRAINT [FK05_ENTITY_PROCESSED_SNAPSHOTS_UTC_TO_ENTITY] FOREIGN KEY([COD_ENTITY])
REFERENCES [MDAPEL].[ENTITY] ([COD_ENTITY])
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC] CHECK CONSTRAINT [FK05_ENTITY_PROCESSED_SNAPSHOTS_UTC_TO_ENTITY]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]  WITH CHECK ADD  CONSTRAINT [FK06_ENTITY_PROCESSED_SNAPSHOTS_UTC_TO_SOR] FOREIGN KEY([COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC] CHECK CONSTRAINT [FK06_ENTITY_PROCESSED_SNAPSHOTS_UTC_TO_SOR]
GO
ALTER TABLE [MDAPEL].[FUNCTION]  WITH CHECK ADD  CONSTRAINT [FK01_FUNCTION_TO_SUBJECT] FOREIGN KEY([COD_SUBJECT])
REFERENCES [MDAPEL].[SUBJECT] ([COD_SUBJECT])
GO
ALTER TABLE [MDAPEL].[FUNCTION] CHECK CONSTRAINT [FK01_FUNCTION_TO_SUBJECT]
GO
ALTER TABLE [MDAPEL].[FUNCTION]  WITH CHECK ADD  CONSTRAINT [FK02_FUNCTION_TO_DOM_FUNCTION_TYPE] FOREIGN KEY([COD_FUNCTION_TYPE])
REFERENCES [MDAPEL].[DOM_FUNCTION_TYPE] ([COD_FUNCTION_TYPE])
GO
ALTER TABLE [MDAPEL].[FUNCTION] CHECK CONSTRAINT [FK02_FUNCTION_TO_DOM_FUNCTION_TYPE]
GO
ALTER TABLE [MDAPEL].[FUNCTION]  WITH CHECK ADD  CONSTRAINT [FK03_FUNCTION_TO_DOM_GENERIC_SPECIFIC] FOREIGN KEY([IND_GENERIC_SPECIFIC])
REFERENCES [MDAPEL].[DOM_GENERIC_SPECIFIC] ([IND_GENERIC_SPECIFIC])
GO
ALTER TABLE [MDAPEL].[FUNCTION] CHECK CONSTRAINT [FK03_FUNCTION_TO_DOM_GENERIC_SPECIFIC]
GO
ALTER TABLE [MDAPEL].[FUNCTION_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK01_FUNCTION_PROCESS__TO_FUNCTION] FOREIGN KEY([COD_FUNCTION])
REFERENCES [MDAPEL].[FUNCTION] ([COD_FUNCTION])
GO
ALTER TABLE [MDAPEL].[FUNCTION_PROCESS] CHECK CONSTRAINT [FK01_FUNCTION_PROCESS__TO_FUNCTION]
GO
ALTER TABLE [MDAPEL].[FUNCTION_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK02_FUNCTION_PROCESS_TO_PROCESS] FOREIGN KEY([COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[FUNCTION_PROCESS] CHECK CONSTRAINT [FK02_FUNCTION_PROCESS_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[INSTANCE]  WITH CHECK ADD  CONSTRAINT [FK02_INSTANCE_TO_PROCESS] FOREIGN KEY([COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[INSTANCE] CHECK CONSTRAINT [FK02_INSTANCE_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[INSTANCE]  WITH CHECK ADD  CONSTRAINT [FK03_INSTANCE_TO_DOM_INSTANCE_STATUS] FOREIGN KEY([COD_INSTANCE_STATUS])
REFERENCES [MDAPEL].[DOM_INSTANCE_STATUS] ([COD_INSTANCE_STATUS])
GO
ALTER TABLE [MDAPEL].[INSTANCE] CHECK CONSTRAINT [FK03_INSTANCE_TO_DOM_INSTANCE_STATUS]
GO
ALTER TABLE [MDAPEL].[LOG]  WITH CHECK ADD  CONSTRAINT [FK01_LOG_TO_PROCESS] FOREIGN KEY([COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[LOG] CHECK CONSTRAINT [FK01_LOG_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[LOG]  WITH CHECK ADD  CONSTRAINT [FK02_LOG_TO_INSTANCE] FOREIGN KEY([COD_INSTANCE])
REFERENCES [MDAPEL].[INSTANCE] ([COD_INSTANCE])
GO
ALTER TABLE [MDAPEL].[LOG] CHECK CONSTRAINT [FK02_LOG_TO_INSTANCE]
GO
ALTER TABLE [MDAPEL].[LOG]  WITH CHECK ADD  CONSTRAINT [FK03_LOG_TO_DOM_LOG_TYPE] FOREIGN KEY([COD_LOG_TYPE])
REFERENCES [MDAPEL].[DOM_LOG_TYPE] ([COD_LOG_TYPE])
GO
ALTER TABLE [MDAPEL].[LOG] CHECK CONSTRAINT [FK03_LOG_TO_DOM_LOG_TYPE]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [FK01_PROCESS_TO_SUBJECT] FOREIGN KEY([COD_SUBJECT])
REFERENCES [MDAPEL].[SUBJECT] ([COD_SUBJECT])
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [FK01_PROCESS_TO_SUBJECT]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [FK02_PROCESS_TO_DOM_BOOLEAN1] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [FK02_PROCESS_TO_DOM_BOOLEAN1]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [FK03_PROCESS_TO_DOM_BOOLEAN2] FOREIGN KEY([IND_INSTANCE_RUNNING])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [FK03_PROCESS_TO_DOM_BOOLEAN2]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [FK04_PROCESS_TO_DOM_PROCESS_ENGINE] FOREIGN KEY([COD_PROCESS_ENGINE])
REFERENCES [MDAPEL].[DOM_PROCESS_ENGINE] ([COD_PROCESS_ENGINE])
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [FK04_PROCESS_TO_DOM_PROCESS_ENGINE]
GO
ALTER TABLE [MDAPEL].[SOR]  WITH CHECK ADD  CONSTRAINT [FK01_SOR_TO_SUBJECT] FOREIGN KEY([COD_SUBJECT])
REFERENCES [MDAPEL].[SUBJECT] ([COD_SUBJECT])
GO
ALTER TABLE [MDAPEL].[SOR] CHECK CONSTRAINT [FK01_SOR_TO_SUBJECT]
GO
ALTER TABLE [MDAPEL].[SUBJECT]  WITH CHECK ADD  CONSTRAINT [FK01_SUBJECT_TO_AREA] FOREIGN KEY([COD_AREA])
REFERENCES [MDAPEL].[AREA] ([COD_AREA])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [MDAPEL].[SUBJECT] CHECK CONSTRAINT [FK01_SUBJECT_TO_AREA]
GO
ALTER TABLE [MDAPEL].[SUBJECT]  WITH CHECK ADD  CONSTRAINT [FK02_SUBJECT_TO_DOM_SUBJECT_TYPE] FOREIGN KEY([COD_SUBJECT_TYPE])
REFERENCES [MDAPEL].[DOM_SUBJECT_TYPE] ([COD_SUBJECT_TYPE])
GO
ALTER TABLE [MDAPEL].[SUBJECT] CHECK CONSTRAINT [FK02_SUBJECT_TO_DOM_SUBJECT_TYPE]
GO
ALTER TABLE [MDAPEL].[SUBJECT]  WITH CHECK ADD  CONSTRAINT [FK03_SUBJECT_TO_DOM_BOOLEAN] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[SUBJECT] CHECK CONSTRAINT [FK03_SUBJECT_TO_DOM_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[USER]  WITH CHECK ADD  CONSTRAINT [FK01_USER_TO_DOM_BOOLEAN] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[USER] CHECK CONSTRAINT [FK01_USER_TO_DOM_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[USER]  WITH CHECK ADD  CONSTRAINT [FK02_USER_TO_DOM_GENDER] FOREIGN KEY([IND_GENDER])
REFERENCES [MDAPEL].[DOM_GENDER] ([IND_GENDER])
GO
ALTER TABLE [MDAPEL].[USER] CHECK CONSTRAINT [FK02_USER_TO_DOM_GENDER]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [CK__ATTRIBUTE__IND_A__17036CC0] CHECK  (([IND_ATTRIBUTE_IS_NULLABLE]='Y' OR [IND_ATTRIBUTE_IS_NULLABLE]='N' OR [IND_ATTRIBUTE_IS_NULLABLE]='?'))
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [CK__ATTRIBUTE__IND_A__17036CC0]
GO
ALTER TABLE [MDAPEL].[DOMAIN]  WITH CHECK ADD  CONSTRAINT [CK__DOMAIN__IND_GENE__60D24498] CHECK  (([IND_GENERIC_SPECIFIC]='G' OR [IND_GENERIC_SPECIFIC]='S'))
GO
ALTER TABLE [MDAPEL].[DOMAIN] CHECK CONSTRAINT [CK__DOMAIN__IND_GENE__60D24498]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [CN30_DOMAIN_TRANSLATION] CHECK  (([QTY_DOMAIN_FROM]=(1) OR [QTY_DOMAIN_FROM]=(1) OR [QTY_DOMAIN_FROM]=(2) OR [QTY_DOMAIN_FROM]=(3) OR [QTY_DOMAIN_FROM]=(4) OR [QTY_DOMAIN_FROM]=(5) OR [QTY_DOMAIN_FROM]=(6) OR [QTY_DOMAIN_FROM]=(7) OR [QTY_DOMAIN_FROM]=(9) OR [QTY_DOMAIN_FROM]=(10)))
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [CN30_DOMAIN_TRANSLATION]
GO
ALTER TABLE [MDAPEL].[ENTITY]  WITH CHECK ADD  CONSTRAINT [CK__ENTITY__COD_ENTI__663ED4F0] CHECK  (([COD_ENTITY_TYPE]='TABLE' OR [COD_ENTITY_TYPE]='DOCUMENT' OR [COD_ENTITY_TYPE]='OTHER'))
GO
ALTER TABLE [MDAPEL].[ENTITY] CHECK CONSTRAINT [CK__ENTITY__COD_ENTI__663ED4F0]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [CN21_IND_INSTANCE_RUNNING] CHECK  (([IND_INSTANCE_RUNNING]='N' OR [IND_INSTANCE_RUNNING]='Y'))
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [CN21_IND_INSTANCE_RUNNING]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [CN22_IND_ACTIVATED] CHECK  (([IND_ACTIVATED]='N' OR [IND_ACTIVATED]='Y'))
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [CN22_IND_ACTIVATED]
GO

