/****** Object:  Index [UK03_ATTRIBUTE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK03_ATTRIBUTE] ON [MDAPEL].[ATTRIBUTE]
(
	[COD_ENTITY] ASC,
	[NAM_ATTRIBUTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX03_DOMAIN_TRANSLATION_VALUE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX03_DOMAIN_TRANSLATION_VALUE] ON [MDAPEL].[DOMAIN_TRANSLATION_VALUE]
(
	[COD_DOMAIN_TRANSLATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK02_DOMAIN_TRANSLATION_VALUE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK02_DOMAIN_TRANSLATION_VALUE] ON [MDAPEL].[DOMAIN_TRANSLATION_VALUE]
(
	[COD_DOMAIN_TRANSLATION] ASC,
	[COD_DOMAIN_VALUE_FROM_01] ASC,
	[COD_DOMAIN_VALUE_FROM_02] ASC,
	[COD_DOMAIN_VALUE_FROM_03] ASC,
	[COD_DOMAIN_VALUE_FROM_04] ASC,
	[COD_DOMAIN_VALUE_FROM_05] ASC,
	[COD_DOMAIN_VALUE_TOO] ASC,
	[DAT_END] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK01_ENTITY]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK01_ENTITY] ON [MDAPEL].[ENTITY]
(
	[COD_SUBJECT] ASC,
	[NAM_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX02_ENTITY_PROCESSED_SNAPSHOTS_DAT]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX02_ENTITY_PROCESSED_SNAPSHOTS_DAT] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]
(
	[COD_SOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX03_ENTITY_PROCESSED_SNAPSHOTS_DAT]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX03_ENTITY_PROCESSED_SNAPSHOTS_DAT] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]
(
	[DAT_SNAPSHOT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX04_ENTITY_PROCESSED_SNAPSHOTS_DAT]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX04_ENTITY_PROCESSED_SNAPSHOTS_DAT] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]
(
	[COD_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX02_ENTITY_PROCESSED_SNAPSHOTS_UTC]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX02_ENTITY_PROCESSED_SNAPSHOTS_UTC] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]
(
	[COD_SOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX03_ENTITY_PROCESSED_SNAPSHOTS_UTC]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX03_ENTITY_PROCESSED_SNAPSHOTS_UTC] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]
(
	[UTC_SNAPSHOT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX04_ENTITY_PROCESSED_SNAPSHOTS_UTC]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX04_ENTITY_PROCESSED_SNAPSHOTS_UTC] ON [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]
(
	[COD_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX01_INSTANCE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX01_INSTANCE] ON [MDAPEL].[INSTANCE]
(
	[COD_PROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX10_LOG_COD_PROCESS]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX10_LOG_COD_PROCESS] ON [MDAPEL].[LOG]
(
	[COD_PROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX11_LOG_COD_INSTANCE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX11_LOG_COD_INSTANCE] ON [MDAPEL].[LOG]
(
	[COD_INSTANCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX12_LOG_COD_LOG_TYPE]    Script Date: 2/19/2013 12:38:17 PM ******/
CREATE NONCLUSTERED INDEX [IX12_LOG_COD_LOG_TYPE] ON [MDAPEL].[LOG]
(
	[COD_LOG_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] ADD  CONSTRAINT [CN04_HUB_ASSOCIATION]  DEFAULT ((0)) FOR [COD_ASSOCIATION_RECURSIVE]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] ADD  CONSTRAINT [CN02_HUB_ASSOCIATION]  DEFAULT ((0)) FOR [M_COD_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] ADD  CONSTRAINT [CN03_HUB_ASSOCIATION]  DEFAULT (getutcdate()) FOR [M_UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC] ADD  CONSTRAINT [CN01_DOM_HUB_IDC]  DEFAULT (getutcdate()) FOR [M_UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE] ADD  CONSTRAINT [CN02_HUB_OBJECTROLE]  DEFAULT ((0)) FOR [M_COD_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE] ADD  CONSTRAINT [CN03_HUB_OBJECTROLE]  DEFAULT (getutcdate()) FOR [M_UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[DOM_SCENARIO] ADD  CONSTRAINT [CN01_DOM_SCENARIO]  DEFAULT (getutcdate()) FOR [M_UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((1)) FOR [QTY_DOMAIN_FROM]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((-2)) FOR [COD_DOMAIN_FROM_02]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((-2)) FOR [COD_DOMAIN_FROM_03]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((-2)) FOR [COD_DOMAIN_FROM_04]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] ADD  DEFAULT ((-2)) FOR [COD_DOMAIN_FROM_05]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__0D3AD6BB]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_01]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__0E2EFAF4]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_02]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__0F231F2D]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_03]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__10174366]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_04]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__110B679F]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_FROM_05]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] ADD  CONSTRAINT [DF__DOMAIN_TR__COD_D__16C440F5]  DEFAULT ('_#_') FOR [COD_DOMAIN_VALUE_TOO]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT] ADD  CONSTRAINT [CN01_ENTITY_PROCESSED_SNAPSHOTS_DAT_M_UTC_RECORD_INSERTED]  DEFAULT (getutcdate()) FOR [UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC] ADD  CONSTRAINT [CN01_ENTITY_PROCESSED_SNAPSHOTS_UTC_M_UTC_RECORD_INSERTED]  DEFAULT (getutcdate()) FOR [UTC_RECORD_INSERTED]
GO
ALTER TABLE [MDAPEL].[LOG] ADD  CONSTRAINT [CN09_LOG_UTCDATE]  DEFAULT (getutcdate()) FOR [UTC_LOG]
GO
ALTER TABLE [MDAPEL].[AREA]  WITH CHECK ADD  CONSTRAINT [FK01_AREA_TO_DOMAIN_BOOLEAN] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[AREA] CHECK CONSTRAINT [FK01_AREA_TO_DOMAIN_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK01_ATTRIBUTE_TO_ENTITY] FOREIGN KEY([COD_ENTITY])
REFERENCES [MDAPEL].[ENTITY] ([COD_ENTITY])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [FK01_ATTRIBUTE_TO_ENTITY]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK02_ATTRIBUTE_TO_DOM_BOOLEAN] FOREIGN KEY([IND_ATTRIBUTE_IS_NULLABLE])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [FK02_ATTRIBUTE_TO_DOM_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK04_ATTRIBUTE_TO_DOM_ATTRIBUTE_TYPE] FOREIGN KEY([COD_ATTRIBUTE_TYPE])
REFERENCES [MDAPEL].[DOM_ATTRIBUTE_TYPE] ([COD_ATTRIBUTE_TYPE])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [FK04_ATTRIBUTE_TO_DOM_ATTRIBUTE_TYPE]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK05_ATTRIBUTE_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [FK05_ATTRIBUTE_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK01_ATTRIBUTE_PROCESS_TO_ATTRIBUTE] FOREIGN KEY([COD_ATTRIBUTE])
REFERENCES [MDAPEL].[ATTRIBUTE] ([COD_ATTRIBUTE])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS] CHECK CONSTRAINT [FK01_ATTRIBUTE_PROCESS_TO_ATTRIBUTE]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK02_ATTRIBUTE_PROCESS_TO_PROCESS] FOREIGN KEY([COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS] CHECK CONSTRAINT [FK02_ATTRIBUTE_PROCESS_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK03_ATTRIBUTE_PROCESS_TO_DOM_INPUT_OUTPUT] FOREIGN KEY([IND_INPUT_OUTPUT])
REFERENCES [MDAPEL].[DOM_INPUT_OUTPUT] ([IND_INPUT_OUTPUT])
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE_PROCESS] CHECK CONSTRAINT [FK03_ATTRIBUTE_PROCESS_TO_DOM_INPUT_OUTPUT]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [FK01_DOM_ASSOCIATION_TO_MDAPEL_PROCESS] FOREIGN KEY([M_COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] CHECK CONSTRAINT [FK01_DOM_ASSOCIATION_TO_MDAPEL_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [FK02_DOM_ASSOCIATION_TO_DOM_ASSOCIATION] FOREIGN KEY([COD_ASSOCIATION_RECURSIVE])
REFERENCES [MDAPEL].[DOM_ASSOCIATION] ([COD_ASSOCIATION])
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] CHECK CONSTRAINT [FK02_DOM_ASSOCIATION_TO_DOM_ASSOCIATION]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [FK03_DOM_ASSOCIATION_TO_DOM_HUB_ENTITY] FOREIGN KEY([COD_HUB_ENTITY_1])
REFERENCES [MDAPEL].[DOM_HUB_ENTITY] ([COD_HUB_ENTITY])
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] CHECK CONSTRAINT [FK03_DOM_ASSOCIATION_TO_DOM_HUB_ENTITY]
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [FK04_DOM_ASSOCIATION_TO_DOM_HUB_ENTITY] FOREIGN KEY([COD_HUB_ENTITY_2])
REFERENCES [MDAPEL].[DOM_HUB_ENTITY] ([COD_HUB_ENTITY])
GO
ALTER TABLE [MDAPEL].[DOM_ASSOCIATION] CHECK CONSTRAINT [FK04_DOM_ASSOCIATION_TO_DOM_HUB_ENTITY]
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC]  WITH CHECK ADD  CONSTRAINT [FK02_DOM_HUB_IDC_TO_PROCESS] FOREIGN KEY([M_COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC] CHECK CONSTRAINT [FK02_DOM_HUB_IDC_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC]  WITH CHECK ADD  CONSTRAINT [FK03_DOM_HUB_IDC_TO_SOR] FOREIGN KEY([M_COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC] CHECK CONSTRAINT [FK03_DOM_HUB_IDC_TO_SOR]
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC]  WITH CHECK ADD  CONSTRAINT [FK04_DOM_HUB_IDC_TO_DOM_HUB_ENTITY] FOREIGN KEY([COD_HUB_ENTITY])
REFERENCES [MDAPEL].[DOM_HUB_ENTITY] ([COD_HUB_ENTITY])
GO
ALTER TABLE [MDAPEL].[DOM_HUB_IDC] CHECK CONSTRAINT [FK04_DOM_HUB_IDC_TO_DOM_HUB_ENTITY]
GO
ALTER TABLE [MDAPEL].[DOM_INSTANCE_STATUS]  WITH CHECK ADD  CONSTRAINT [FK_DOM_INSTANCE_STATUS_DOM_INSTANCE_STATUS] FOREIGN KEY([COD_INSTANCE_STATUS])
REFERENCES [MDAPEL].[DOM_INSTANCE_STATUS] ([COD_INSTANCE_STATUS])
GO
ALTER TABLE [MDAPEL].[DOM_INSTANCE_STATUS] CHECK CONSTRAINT [FK_DOM_INSTANCE_STATUS_DOM_INSTANCE_STATUS]
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE]  WITH CHECK ADD  CONSTRAINT [FK01_HUB_OBJECTROLE_TO_PROCESS] FOREIGN KEY([M_COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE] CHECK CONSTRAINT [FK01_HUB_OBJECTROLE_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE]  WITH CHECK ADD  CONSTRAINT [FK02_HUB_OBJECTROLE_TO_DOM_HUB_ENTITY] FOREIGN KEY([COD_HUB_ENTITY])
REFERENCES [MDAPEL].[DOM_HUB_ENTITY] ([COD_HUB_ENTITY])
GO
ALTER TABLE [MDAPEL].[DOM_OBJECTROLE] CHECK CONSTRAINT [FK02_HUB_OBJECTROLE_TO_DOM_HUB_ENTITY]
GO
ALTER TABLE [MDAPEL].[DOMAIN]  WITH CHECK ADD  CONSTRAINT [FK01_DOMAIN_TO_SOR] FOREIGN KEY([COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[DOMAIN] CHECK CONSTRAINT [FK01_DOMAIN_TO_SOR]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK01_DOMAIN_TRANSLATION_TO_DOM_QTY_DOMAIN_FROM] FOREIGN KEY([QTY_DOMAIN_FROM])
REFERENCES [MDAPEL].[DOM_QTY_DOMAIN_FROM] ([QTY_DOMAIN_FROM])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK01_DOMAIN_TRANSLATION_TO_DOM_QTY_DOMAIN_FROM]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK11_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_01])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK11_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK12_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_02])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK12_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK13_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_03])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK13_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK14_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_04])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK14_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK15_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_FROM_05])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK15_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [FK21_DOMAIN_TRANSLATION_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN_TOO])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [FK21_DOMAIN_TRANSLATION_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE]  WITH CHECK ADD  CONSTRAINT [FK01_DOMAIN_TRANSLATION_VALUE] FOREIGN KEY([COD_DOMAIN_TRANSLATION])
REFERENCES [MDAPEL].[DOMAIN_TRANSLATION] ([COD_DOMAIN_TRANSLATION])
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION_VALUE] CHECK CONSTRAINT [FK01_DOMAIN_TRANSLATION_VALUE]
GO
ALTER TABLE [MDAPEL].[DOMAIN_VALUE]  WITH CHECK ADD  CONSTRAINT [FK01_DOMAIN_VALUE_TO_DOMAIN] FOREIGN KEY([COD_DOMAIN])
REFERENCES [MDAPEL].[DOMAIN] ([COD_DOMAIN])
GO
ALTER TABLE [MDAPEL].[DOMAIN_VALUE] CHECK CONSTRAINT [FK01_DOMAIN_VALUE_TO_DOMAIN]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK01_DTI_TO_ENTITY] FOREIGN KEY([COD_ENTITY])
REFERENCES [MDAPEL].[ENTITY] ([COD_ENTITY])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK01_DTI_TO_ENTITY]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK02_DTI_TO_SOR] FOREIGN KEY([COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK02_DTI_TO_SOR]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK03_DTI_TO_DOM_BOOLEAN] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK03_DTI_TO_DOM_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK04_DTI_TO_DOM_DTI_TYPE] FOREIGN KEY([COD_DTI_TYPE])
REFERENCES [MDAPEL].[DOM_DTI_TYPE] ([COD_DTI_TYPE])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK04_DTI_TO_DOM_DTI_TYPE]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK05_DTI_TO_DOM_DTI_CONTAINER_TYPE] FOREIGN KEY([COD_DTI_CONTAINER_TYPE])
REFERENCES [MDAPEL].[DOM_DTI_CONTAINER_TYPE] ([COD_DTI_CONTAINER_TYPE])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK05_DTI_TO_DOM_DTI_CONTAINER_TYPE]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK06_DTI_TO_DOM_DTI_FREQUENCY] FOREIGN KEY([COD_DTI_FREQUENCY])
REFERENCES [MDAPEL].[DOM_DTI_FREQUENCY] ([COD_DTI_FREQUENCY])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK06_DTI_TO_DOM_DTI_FREQUENCY]
GO
ALTER TABLE [MDAPEL].[DTI]  WITH CHECK ADD  CONSTRAINT [FK07_DTI_TO_DOM_DTI_TRANSFER_PROTOCOL] FOREIGN KEY([COD_DTI_TRANSFER_PROTOCOL])
REFERENCES [MDAPEL].[DOM_DTI_TRANSFER_PROTOCOL] ([COD_DTI_TRANSFER_PROTOCOL])
GO
ALTER TABLE [MDAPEL].[DTI] CHECK CONSTRAINT [FK07_DTI_TO_DOM_DTI_TRANSFER_PROTOCOL]
GO
ALTER TABLE [MDAPEL].[ENTITY]  WITH CHECK ADD  CONSTRAINT [FK02_ENTITY_TO_SUBJECT] FOREIGN KEY([COD_SUBJECT])
REFERENCES [MDAPEL].[SUBJECT] ([COD_SUBJECT])
GO
ALTER TABLE [MDAPEL].[ENTITY] CHECK CONSTRAINT [FK02_ENTITY_TO_SUBJECT]
GO
ALTER TABLE [MDAPEL].[ENTITY]  WITH CHECK ADD  CONSTRAINT [FK03_ENTITY_TO_DOM_ENTITY_TYPE] FOREIGN KEY([COD_ENTITY_TYPE])
REFERENCES [MDAPEL].[DOM_ENTITY_TYPE] ([COD_ENTITY_TYPE])
GO
ALTER TABLE [MDAPEL].[ENTITY] CHECK CONSTRAINT [FK03_ENTITY_TO_DOM_ENTITY_TYPE]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]  WITH CHECK ADD  CONSTRAINT [FK05_ENTITY_PROCESSED_SNAPSHOTS_DAT_TO_ENTITY] FOREIGN KEY([COD_ENTITY])
REFERENCES [MDAPEL].[ENTITY] ([COD_ENTITY])
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT] CHECK CONSTRAINT [FK05_ENTITY_PROCESSED_SNAPSHOTS_DAT_TO_ENTITY]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT]  WITH CHECK ADD  CONSTRAINT [FK06_ENTITY_PROCESSED_SNAPSHOTS_DAT_TO_SOR] FOREIGN KEY([COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_DAT] CHECK CONSTRAINT [FK06_ENTITY_PROCESSED_SNAPSHOTS_DAT_TO_SOR]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]  WITH CHECK ADD  CONSTRAINT [FK05_ENTITY_PROCESSED_SNAPSHOTS_UTC_TO_ENTITY] FOREIGN KEY([COD_ENTITY])
REFERENCES [MDAPEL].[ENTITY] ([COD_ENTITY])
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC] CHECK CONSTRAINT [FK05_ENTITY_PROCESSED_SNAPSHOTS_UTC_TO_ENTITY]
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]  WITH CHECK ADD  CONSTRAINT [FK06_ENTITY_PROCESSED_SNAPSHOTS_UTC_TO_SOR] FOREIGN KEY([COD_SOR])
REFERENCES [MDAPEL].[SOR] ([COD_SOR])
GO
ALTER TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC] CHECK CONSTRAINT [FK06_ENTITY_PROCESSED_SNAPSHOTS_UTC_TO_SOR]
GO
ALTER TABLE [MDAPEL].[FUNCTION]  WITH CHECK ADD  CONSTRAINT [FK01_FUNCTION_TO_SUBJECT] FOREIGN KEY([COD_SUBJECT])
REFERENCES [MDAPEL].[SUBJECT] ([COD_SUBJECT])
GO
ALTER TABLE [MDAPEL].[FUNCTION] CHECK CONSTRAINT [FK01_FUNCTION_TO_SUBJECT]
GO
ALTER TABLE [MDAPEL].[FUNCTION]  WITH CHECK ADD  CONSTRAINT [FK02_FUNCTION_TO_DOM_FUNCTION_TYPE] FOREIGN KEY([COD_FUNCTION_TYPE])
REFERENCES [MDAPEL].[DOM_FUNCTION_TYPE] ([COD_FUNCTION_TYPE])
GO
ALTER TABLE [MDAPEL].[FUNCTION] CHECK CONSTRAINT [FK02_FUNCTION_TO_DOM_FUNCTION_TYPE]
GO
ALTER TABLE [MDAPEL].[FUNCTION]  WITH CHECK ADD  CONSTRAINT [FK03_FUNCTION_TO_DOM_GENERIC_SPECIFIC] FOREIGN KEY([IND_GENERIC_SPECIFIC])
REFERENCES [MDAPEL].[DOM_GENERIC_SPECIFIC] ([IND_GENERIC_SPECIFIC])
GO
ALTER TABLE [MDAPEL].[FUNCTION] CHECK CONSTRAINT [FK03_FUNCTION_TO_DOM_GENERIC_SPECIFIC]
GO
ALTER TABLE [MDAPEL].[FUNCTION_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK01_FUNCTION_PROCESS__TO_FUNCTION] FOREIGN KEY([COD_FUNCTION])
REFERENCES [MDAPEL].[FUNCTION] ([COD_FUNCTION])
GO
ALTER TABLE [MDAPEL].[FUNCTION_PROCESS] CHECK CONSTRAINT [FK01_FUNCTION_PROCESS__TO_FUNCTION]
GO
ALTER TABLE [MDAPEL].[FUNCTION_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK02_FUNCTION_PROCESS_TO_PROCESS] FOREIGN KEY([COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[FUNCTION_PROCESS] CHECK CONSTRAINT [FK02_FUNCTION_PROCESS_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[INSTANCE]  WITH CHECK ADD  CONSTRAINT [FK02_INSTANCE_TO_PROCESS] FOREIGN KEY([COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[INSTANCE] CHECK CONSTRAINT [FK02_INSTANCE_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[INSTANCE]  WITH CHECK ADD  CONSTRAINT [FK03_INSTANCE_TO_DOM_INSTANCE_STATUS] FOREIGN KEY([COD_INSTANCE_STATUS])
REFERENCES [MDAPEL].[DOM_INSTANCE_STATUS] ([COD_INSTANCE_STATUS])
GO
ALTER TABLE [MDAPEL].[INSTANCE] CHECK CONSTRAINT [FK03_INSTANCE_TO_DOM_INSTANCE_STATUS]
GO
ALTER TABLE [MDAPEL].[LOG]  WITH CHECK ADD  CONSTRAINT [FK01_LOG_TO_PROCESS] FOREIGN KEY([COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO
ALTER TABLE [MDAPEL].[LOG] CHECK CONSTRAINT [FK01_LOG_TO_PROCESS]
GO
ALTER TABLE [MDAPEL].[LOG]  WITH CHECK ADD  CONSTRAINT [FK02_LOG_TO_INSTANCE] FOREIGN KEY([COD_INSTANCE])
REFERENCES [MDAPEL].[INSTANCE] ([COD_INSTANCE])
GO
ALTER TABLE [MDAPEL].[LOG] CHECK CONSTRAINT [FK02_LOG_TO_INSTANCE]
GO
ALTER TABLE [MDAPEL].[LOG]  WITH CHECK ADD  CONSTRAINT [FK03_LOG_TO_DOM_LOG_TYPE] FOREIGN KEY([COD_LOG_TYPE])
REFERENCES [MDAPEL].[DOM_LOG_TYPE] ([COD_LOG_TYPE])
GO
ALTER TABLE [MDAPEL].[LOG] CHECK CONSTRAINT [FK03_LOG_TO_DOM_LOG_TYPE]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [FK01_PROCESS_TO_SUBJECT] FOREIGN KEY([COD_SUBJECT])
REFERENCES [MDAPEL].[SUBJECT] ([COD_SUBJECT])
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [FK01_PROCESS_TO_SUBJECT]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [FK02_PROCESS_TO_DOM_BOOLEAN1] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [FK02_PROCESS_TO_DOM_BOOLEAN1]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [FK03_PROCESS_TO_DOM_BOOLEAN2] FOREIGN KEY([IND_INSTANCE_RUNNING])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [FK03_PROCESS_TO_DOM_BOOLEAN2]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [FK04_PROCESS_TO_DOM_PROCESS_ENGINE] FOREIGN KEY([COD_PROCESS_ENGINE])
REFERENCES [MDAPEL].[DOM_PROCESS_ENGINE] ([COD_PROCESS_ENGINE])
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [FK04_PROCESS_TO_DOM_PROCESS_ENGINE]
GO
ALTER TABLE [MDAPEL].[SOR]  WITH CHECK ADD  CONSTRAINT [FK01_SOR_TO_SUBJECT] FOREIGN KEY([COD_SUBJECT])
REFERENCES [MDAPEL].[SUBJECT] ([COD_SUBJECT])
GO
ALTER TABLE [MDAPEL].[SOR] CHECK CONSTRAINT [FK01_SOR_TO_SUBJECT]
GO
ALTER TABLE [MDAPEL].[SUBJECT]  WITH CHECK ADD  CONSTRAINT [FK01_SUBJECT_TO_AREA] FOREIGN KEY([COD_AREA])
REFERENCES [MDAPEL].[AREA] ([COD_AREA])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [MDAPEL].[SUBJECT] CHECK CONSTRAINT [FK01_SUBJECT_TO_AREA]
GO
ALTER TABLE [MDAPEL].[SUBJECT]  WITH CHECK ADD  CONSTRAINT [FK02_SUBJECT_TO_DOM_SUBJECT_TYPE] FOREIGN KEY([COD_SUBJECT_TYPE])
REFERENCES [MDAPEL].[DOM_SUBJECT_TYPE] ([COD_SUBJECT_TYPE])
GO
ALTER TABLE [MDAPEL].[SUBJECT] CHECK CONSTRAINT [FK02_SUBJECT_TO_DOM_SUBJECT_TYPE]
GO
ALTER TABLE [MDAPEL].[SUBJECT]  WITH CHECK ADD  CONSTRAINT [FK03_SUBJECT_TO_DOM_BOOLEAN] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[SUBJECT] CHECK CONSTRAINT [FK03_SUBJECT_TO_DOM_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[USER]  WITH CHECK ADD  CONSTRAINT [FK01_USER_TO_DOM_BOOLEAN] FOREIGN KEY([IND_ACTIVATED])
REFERENCES [MDAPEL].[DOM_BOOLEAN] ([IND_YES_NO])
GO
ALTER TABLE [MDAPEL].[USER] CHECK CONSTRAINT [FK01_USER_TO_DOM_BOOLEAN]
GO
ALTER TABLE [MDAPEL].[USER]  WITH CHECK ADD  CONSTRAINT [FK02_USER_TO_DOM_GENDER] FOREIGN KEY([IND_GENDER])
REFERENCES [MDAPEL].[DOM_GENDER] ([IND_GENDER])
GO
ALTER TABLE [MDAPEL].[USER] CHECK CONSTRAINT [FK02_USER_TO_DOM_GENDER]
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [CK__ATTRIBUTE__IND_A__17036CC0] CHECK  (([IND_ATTRIBUTE_IS_NULLABLE]='Y' OR [IND_ATTRIBUTE_IS_NULLABLE]='N' OR [IND_ATTRIBUTE_IS_NULLABLE]='?'))
GO
ALTER TABLE [MDAPEL].[ATTRIBUTE] CHECK CONSTRAINT [CK__ATTRIBUTE__IND_A__17036CC0]
GO
ALTER TABLE [MDAPEL].[DOMAIN]  WITH CHECK ADD  CONSTRAINT [CK__DOMAIN__IND_GENE__60D24498] CHECK  (([IND_GENERIC_SPECIFIC]='G' OR [IND_GENERIC_SPECIFIC]='S'))
GO
ALTER TABLE [MDAPEL].[DOMAIN] CHECK CONSTRAINT [CK__DOMAIN__IND_GENE__60D24498]
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION]  WITH CHECK ADD  CONSTRAINT [CN30_DOMAIN_TRANSLATION] CHECK  (([QTY_DOMAIN_FROM]=(1) OR [QTY_DOMAIN_FROM]=(1) OR [QTY_DOMAIN_FROM]=(2) OR [QTY_DOMAIN_FROM]=(3) OR [QTY_DOMAIN_FROM]=(4) OR [QTY_DOMAIN_FROM]=(5) OR [QTY_DOMAIN_FROM]=(6) OR [QTY_DOMAIN_FROM]=(7) OR [QTY_DOMAIN_FROM]=(9) OR [QTY_DOMAIN_FROM]=(10)))
GO
ALTER TABLE [MDAPEL].[DOMAIN_TRANSLATION] CHECK CONSTRAINT [CN30_DOMAIN_TRANSLATION]
GO
ALTER TABLE [MDAPEL].[ENTITY]  WITH CHECK ADD  CONSTRAINT [CK__ENTITY__COD_ENTI__663ED4F0] CHECK  (([COD_ENTITY_TYPE]='TABLE' OR [COD_ENTITY_TYPE]='DOCUMENT' OR [COD_ENTITY_TYPE]='OTHER'))
GO
ALTER TABLE [MDAPEL].[ENTITY] CHECK CONSTRAINT [CK__ENTITY__COD_ENTI__663ED4F0]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [CN21_IND_INSTANCE_RUNNING] CHECK  (([IND_INSTANCE_RUNNING]='N' OR [IND_INSTANCE_RUNNING]='Y'))
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [CN21_IND_INSTANCE_RUNNING]
GO
ALTER TABLE [MDAPEL].[PROCESS]  WITH CHECK ADD  CONSTRAINT [CN22_IND_ACTIVATED] CHECK  (([IND_ACTIVATED]='N' OR [IND_ACTIVATED]='Y'))
GO
ALTER TABLE [MDAPEL].[PROCESS] CHECK CONSTRAINT [CN22_IND_ACTIVATED]
GO



ALTER TABLE [MDAPEL].[ENTITY_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK01_ENTITY_PROCESS_TO_ENTITY] FOREIGN KEY([COD_ENTITY])
REFERENCES [MDAPEL].[ENTITY] ([COD_ENTITY])
GO

ALTER TABLE [MDAPEL].[ENTITY_PROCESS] CHECK CONSTRAINT [FK01_ENTITY_PROCESS_TO_ENTITY]
GO


ALTER TABLE [MDAPEL].[ENTITY_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK02_ENTITY_PROCESS_TO_PROCESS] FOREIGN KEY([COD_PROCESS])
REFERENCES [MDAPEL].[PROCESS] ([COD_PROCESS])
GO

ALTER TABLE [MDAPEL].[ENTITY_PROCESS] CHECK CONSTRAINT [FK02_ENTITY_PROCESS_TO_PROCESS]
GO

ALTER TABLE [MDAPEL].[ENTITY_PROCESS]  WITH CHECK ADD  CONSTRAINT [FK03_ENTITY_PROCESS_TO_DOM_INPUT_OUTPUT] FOREIGN KEY([IND_INPUT_OUTPUT])
REFERENCES [MDAPEL].[DOM_INPUT_OUTPUT] ([IND_INPUT_OUTPUT])
GO

ALTER TABLE [MDAPEL].[ENTITY_PROCESS] CHECK CONSTRAINT [FK03_ENTITY_PROCESS_TO_DOM_INPUT_OUTPUT]
GO
