/****** Object:  Table [MDAPEL].[DOM_QTY_DOMAIN_FROM]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_QTY_DOMAIN_FROM](
	[QTY_DOMAIN_FROM] [smallint] NOT NULL,
 CONSTRAINT [PK00_DOM_QTY_DOMAIN_FROM] PRIMARY KEY CLUSTERED 
(
	[QTY_DOMAIN_FROM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]