/****** Object:  Table [MDAPEL].[USER]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[USER](
	[COD_USER] [bigint] IDENTITY(1,1) NOT NULL,
	[NAM_LOGIN] [nvarchar](200) NOT NULL,
	[COD_PASSWORD] [nvarchar](50) NOT NULL,
	[NAM_FIRST_NAMES] [nvarchar](200) NOT NULL,
	[NAM_LAST_NAME_PREFIX] [nvarchar](50) NULL,
	[NAM_LAST_NAME] [nvarchar](200) NOT NULL,
	[IND_GENDER] [nchar](1) NOT NULL,
	[DAT_OF_BIRTH] [date] NOT NULL,
	[IDE_PHONENUMBER_01] [nvarchar](20) NULL,
	[IDE_PHONENUMBER_02] [nvarchar](20) NULL,
	[IDE_EMAIL_01] [nvarchar](200) NULL,
	[IDE_EMAIL_02] [nvarchar](200) NULL,
	[IND_ACTIVATED] [nchar](1) NOT NULL,
 CONSTRAINT [PK00_USER] PRIMARY KEY CLUSTERED 
(
	[COD_USER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]