/****** Object:  Table [MDAPEL].[DOM_PLAUSIBLE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_PLAUSIBLE](
	[COD_PLAUSIBLE] [nchar](1) NOT NULL,
	[DES_PLAUSIBLE] [nvarchar](400) NOT NULL,
 CONSTRAINT [PK00_DOM_PLAUSIBLE] PRIMARY KEY CLUSTERED 
(
	[COD_PLAUSIBLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]