/****** Object:  Table [MDAPEL].[DOM_HUB_ENTITY]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_HUB_ENTITY](
	[COD_HUB_ENTITY] [nvarchar](100) NOT NULL,
	[DES_HUB_ENTITY_UK] [nvarchar](max) NOT NULL,
	[DES_HUB_ENTITY_NL] [nvarchar](max) NULL,
 CONSTRAINT [PK00_DOM_HUB_ENTITY] PRIMARY KEY CLUSTERED 
(
	[COD_HUB_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]