/****** Object:  Table [MDAPEL].[PROCESS]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[PROCESS](
	[COD_PROCESS] [bigint] NOT NULL,
	[COD_SUBJECT] [nchar](6) NOT NULL,
	[IND_INSTANCE_RUNNING] [nchar](1) NOT NULL,
	[IND_ACTIVATED] [nchar](1) NOT NULL,
	[COD_PROCESS_ENGINE] [bigint] NOT NULL,
	[NAM_PROCESS] [nvarchar](200) NOT NULL,
	[DES_PROCESS] [nvarchar](400) NOT NULL,
 CONSTRAINT [PK00_PROCESS] PRIMARY KEY CLUSTERED 
(
	[COD_PROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]