/****** Object:  Table [MDAPEL].[ATTRIBUTE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[ATTRIBUTE](
	[COD_ATTRIBUTE] [nvarchar](408) NOT NULL,
	[COD_ENTITY] [nvarchar](107) NOT NULL,
	[NAM_ATTRIBUTE] [nvarchar](200) NOT NULL,
	[DES_ATTRIBUTE] [nvarchar](max) NOT NULL,
	[IND_ATTRIBUTE_IS_NULLABLE] [nchar](1) NOT NULL,
	[COD_ATTRIBUTE_TYPE] [nvarchar](50) NOT NULL,
	[NUM_ATTRIBUTE_MAXIMUM_LENGTH] [smallint] NOT NULL,
	[NUM_ATTRIBUTE_PRECISION] [tinyint] NOT NULL,
	[NUM_ATTRIBUTE_SCALE] [tinyint] NOT NULL,
	[COD_DOMAIN] [bigint] NOT NULL,
	[DAT_ATTRIBUTE_START] [date] NOT NULL,
	[DAT_ATTRIBUTE_END] [date] NOT NULL,
	[DAT_ATTRIBUTE_LAST_STATUS] [date] NOT NULL,
 CONSTRAINT [PK00_ATTRIBUTE] PRIMARY KEY CLUSTERED 
(
	[COD_ATTRIBUTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
