/****** Object:  Table [MDAPEL].[DOM_GENERIC_SPECIFIC]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_GENERIC_SPECIFIC](
	[IND_GENERIC_SPECIFIC] [nchar](1) NOT NULL,
	[DES_GENERIC_SPECIFIC] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_GENERIC_SPECIFIC] PRIMARY KEY CLUSTERED 
(
	[IND_GENERIC_SPECIFIC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]