/****** Object:  Table [MDAPEL].[FUNCTION]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[FUNCTION](
	[COD_FUNCTION] [bigint] NOT NULL,
	[COD_SUBJECT] [nchar](6) NOT NULL,
	[IND_GENERIC_SPECIFIC] [nchar](1) NOT NULL,
	[NAM_FUNCTION] [nvarchar](200) NOT NULL,
	[DES_FUNCTION] [nvarchar](4000) NOT NULL,
	[COD_FUNCTION_TYPE] [nvarchar](50) NOT NULL,
	[QTY_VERSION_NUMBER] [int] NOT NULL,
	[DAT_VERSION_DATE] [date] NOT NULL,
 CONSTRAINT [PK00_FUNCTION] PRIMARY KEY CLUSTERED 
(
	[COD_FUNCTION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]