/****** Object:  Table [MDAPEL].[DOM_INSTANCE_STATUS]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_INSTANCE_STATUS](
	[COD_INSTANCE_STATUS] [nvarchar](22) NOT NULL,
	[DES_INSTANCE_STATUS] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_INSTANCE_STATUS] PRIMARY KEY CLUSTERED 
(
	[COD_INSTANCE_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]