
/****** Object:  Table [MDAPEL].[AREA]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[AREA](
	[COD_AREA] [nchar](3) NOT NULL,
	[DES_AREA] [nvarchar](400) NOT NULL,
	[IND_ACTIVATED] [nchar](1) NOT NULL,
 CONSTRAINT [PK00_AREA] PRIMARY KEY CLUSTERED 
(
	[COD_AREA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]