/****** Object:  Table [MDAPEL].[VERSION]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[VERSION](
	[COD_VERSION] [int] NOT NULL,
	[DAT_VERSION] [date] NOT NULL,
	[DES_VERSION] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK00_VERSION] PRIMARY KEY CLUSTERED 
(
	[COD_VERSION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
