CREATE TABLE [MDAPEL].[ENTITY_PROCESS](
	[COD_ENTITY] [nvarchar](207) NOT NULL,
	[IND_INPUT_OUTPUT] [nchar](1) NOT NULL,
	[COD_PROCESS] [bigint] NOT NULL,
 CONSTRAINT [PK_ENTITY_PROCESS] PRIMARY KEY CLUSTERED 
(
	[COD_ENTITY] ASC,
	[IND_INPUT_OUTPUT] ASC,
	[COD_PROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]