/****** Object:  Table [MDAPEL].[SOR]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[SOR](
	[COD_SOR] [bigint] NOT NULL,
	[COD_SUBJECT] [nchar](6) NOT NULL,
	[DES_SOR] [nvarchar](400) NOT NULL,
	[DAT_START] [date] NOT NULL,
	[DAT_END] [date] NOT NULL,
	[NAM_SOR_MAINTAINER] [nvarchar](200) NULL,
	[IDE_EMAIL_MAINTAINER] [nvarchar](100) NULL,
	[IDE_PHONE_MAINTAINER] [nvarchar](20) NULL,
	[DES_REMARK] [nvarchar](400) NULL,
 CONSTRAINT [PK00_SOR] PRIMARY KEY CLUSTERED 
(
	[COD_SOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
