/****** Object:  Table [MDAPEL].[DOM_INPUT_OUTPUT]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_INPUT_OUTPUT](
	[IND_INPUT_OUTPUT] [nchar](1) NOT NULL,
	[DES_INPUT_OUTPUT] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK00_DOM_INPU_OUTPUT] PRIMARY KEY CLUSTERED 
(
	[IND_INPUT_OUTPUT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]