/****** Object:  Table [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[ENTITY_PROCESSED_SNAPSHOTS_UTC](
	[COD_ENTITY] [nvarchar](107) NOT NULL,
	[COD_SOR] [bigint] NOT NULL,
	[UTC_SNAPSHOT] [datetime2](0) NOT NULL,
	[UTC_RECORD_INSERTED] [datetime2](0) NOT NULL,
 CONSTRAINT [PK00_ENTITY_PROCESSED_SNAPSHOTS_UTC] PRIMARY KEY CLUSTERED 
(
	[COD_ENTITY] ASC,
	[COD_SOR] ASC,
	[UTC_SNAPSHOT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]