/****** Object:  Table [MDAPEL].[LOG]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[LOG](
	[IDR_LOG] [bigint] IDENTITY(1,1) NOT NULL,
	[COD_PROCESS] [bigint] NOT NULL,
	[COD_INSTANCE] [bigint] NOT NULL,
	[UTC_LOG] [datetime2](7) NOT NULL,
	[COD_LOG_TYPE] [nvarchar](20) NOT NULL,
	[TXT_LOG] [nvarchar](4000) NOT NULL,
 CONSTRAINT [PK00_LOG] PRIMARY KEY CLUSTERED 
(
	[IDR_LOG] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]