/****** Object:  Table [MDAPEL].[ENTITY]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[ENTITY](
	[COD_ENTITY] [nvarchar](107) NOT NULL,
	[COD_SUBJECT] [nchar](6) NOT NULL,
	[NAM_ENTITY] [nvarchar](200) NOT NULL,
	[COD_ENTITY_TYPE] [nvarchar](50) NOT NULL,
	[DES_ENTITY] [nvarchar](max) NULL,
	[DES_DESIGN_REMARKS] [nvarchar](max) NULL,
	[DAT_ENTITY_START] [date] NOT NULL,
	[DAT_ENTITY_END] [date] NOT NULL,
	[DAT_ENTITY_LAST_STATUS] [date] NOT NULL,
	[QTY_NUMBER_OF_ROWS] [bigint] NOT NULL,
	[QTY_DATA_SPACE_IN_KB] [bigint] NOT NULL,
	[QTY_INDEX_SPACE_IN_KB] [bigint] NOT NULL,
	[QTY_UNUSED_SPACE_IN_KB] [bigint] NOT NULL,
	[QTY_TOTAL_SPACE_IN_KB] [bigint] NOT NULL,
 CONSTRAINT [PK00_ENTITY] PRIMARY KEY CLUSTERED 
(
	[COD_ENTITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]