/****** Object:  Table [MDAPEL].[DTI]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DTI](
	[COD_DTI] [bigint] NOT NULL,
	[COD_ENTITY] [nvarchar](107) NOT NULL,
	[COD_SOR] [bigint] NOT NULL,
	[COD_DTI_TYPE] [bigint] NOT NULL,
	[COD_DTI_CONTAINER_TYPE] [bigint] NOT NULL,
	[COD_DTI_FREQUENCY] [bigint] NOT NULL,
	[COD_DTI_TRANSFER_PROTOCOL] [bigint] NOT NULL,
	[DES_DTI] [nvarchar](max) NOT NULL,
	[IND_ACTIVATED] [nchar](1) NOT NULL,
 CONSTRAINT [PK00_DTI] PRIMARY KEY CLUSTERED 
(
	[COD_DTI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]