/****** Object:  Table [MDAPEL].[DOMAIN_VALUE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOMAIN_VALUE](
	[COD_DOMAIN] [bigint] NOT NULL,
	[COD_DOMAIN_VALUE] [nvarchar](50) NOT NULL,
	[DES_DOMAIN_VALUE] [nvarchar](400) NOT NULL,
	[DAT_START] [date] NOT NULL,
	[DAT_END] [date] NOT NULL,
	[DES_DOMAIN_VALUE_NL] [nvarchar](400) NULL,
	[DES_REMARK] [nvarchar](max) NULL,
 CONSTRAINT [PK00_DOMAIN_VALUE] PRIMARY KEY CLUSTERED 
(
	[COD_DOMAIN] ASC,
	[COD_DOMAIN_VALUE] ASC,
	[DAT_START] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
