/****** Object:  Table [MDAPEL].[DOM_PROCESS_ENGINE]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_PROCESS_ENGINE](
	[COD_PROCESS_ENGINE] [bigint] NOT NULL,
	[NAM_PROCESS_ENGINE] [nvarchar](50) NOT NULL,
	[DES_PROCESS_ENGINE] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK00_DOM_PROCESS_TYPE] PRIMARY KEY CLUSTERED 
(
	[COD_PROCESS_ENGINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]