/****** Object:  Table [MDAPEL].[DOM_SCENARIO]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOM_SCENARIO](
	[COD_SCENARIO] [bigint] NOT NULL,
	[DES_SCENARIO] [nvarchar](400) NOT NULL,
	[M_UTC_RECORD_INSERTED] [datetime2](7) NOT NULL,
 CONSTRAINT [PK00_DOM_SCENARIO] PRIMARY KEY CLUSTERED 
(
	[COD_SCENARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]