/****** Object:  Table [MDAPEL].[DOMAIN]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [MDAPEL].[DOMAIN](
	[COD_DOMAIN] [bigint] NOT NULL,
	[IND_GENERIC_SPECIFIC] [nchar](1) NOT NULL,
	[COD_SOR] [bigint] NOT NULL,
	[COD_DOMAIN_MASK] [nvarchar](50) NOT NULL,
	[NAM_DOMAIN] [nvarchar](200) NOT NULL,
	[DES_DOMAIN] [nvarchar](max) NOT NULL,
	[DAT_START] [date] NOT NULL,
	[DAT_END] [date] NOT NULL,
 CONSTRAINT [PK00_DOMAIN] PRIMARY KEY CLUSTERED 
(
	[COD_DOMAIN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]