/****** Object:  View [MDAPEL].[VW_LOG]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [MDAPEL].[VW_LOG] 
AS
SELECT 
 [LOG].IDR_LOG
,[LOG].COD_PROCESS
,[LOG].COD_INSTANCE
,[INSTANCE].COD_INSTANCE_STATUS
,[PROCESS].NAM_PROCESS
,[PROCESS].COD_SUBJECT
,[PROCESS].IND_INSTANCE_RUNNING
,[INSTANCE].UTC_INSTANCE_START
,[INSTANCE].UTC_INSTANCE_END
,[LOG].COD_LOG_TYPE
,[LOG].UTC_LOG
,[LOG].TXT_LOG 
  FROM
(
SELECT *
  FROM [MDAPEL].[LOG]
) [LOG]
INNER JOIN
(
SELECT *
  FROM [MDAPEL].[INSTANCE]
) [INSTANCE]
ON [LOG].[COD_INSTANCE] = [INSTANCE].[COD_INSTANCE]
INNER JOIN
(
SELECT *
  FROM MDAPEL.PROCESS
) [PROCESS]
ON [LOG].[COD_PROCESS] = [PROCESS].[COD_PROCESS]