/****** Object:  View [MDAPEL].[VW_INFRASTRUCTURE_SIZE_ENTITY]    Script Date: 2/19/2013 12:38:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [MDAPEL].[VW_INFRASTRUCTURE_SIZE_ENTITY] 
AS
SELECT 
 COD_SUBJECT
,NAM_ENTITY
,SUM(QTY_NUMBER_OF_ROWS) AS QTY_NUMBER_OF_ROWS
,SUM(QTY_DATA_SPACE_IN_KB/1024/1024)  AS QTY_DATA_SPACE_IN_GB
,SUM(QTY_INDEX_SPACE_IN_KB/1024/1024) AS QTY_INDEX_SPACE_IN_GB
,SUM(QTY_UNUSED_SPACE_IN_KB/1024/1024) AS QTY_UNUSED_SPACE_IN_GB
,SUM(QTY_TOTAL_SPACE_IN_KB/1024/1024) AS QTY_TOTAL_SPACE_IN_GB
  FROM MDAPEL.ENTITY
 WHERE 1=1 
GROUP BY COD_SUBJECT,NAM_ENTITY